### ISSUE TITLE
this page loads only when (non-existent) scripts are enabled(green)

### ISSUE THREAD

**Issue by emanueLczirai** [gorhill/uMatrix#104]
On this webpage `http://feeds.arstechnica.com/arstechnica/index`
When everything is blocked (kinda), loading that page is blank, unless I explicitly enable(green) the Scripts section and reload manually. Screenshots show this:

![lacksscriptnumber](https://cloud.githubusercontent.com/assets/5661825/5734191/a8d12cea-9bb0-11e4-9f1f-bb9ad4da54ba.png)
and after I green the Scripts section, manually reload, looks like this:
![nowitloads](https://cloud.githubusercontent.com/assets/5661825/5734193/ae4e8d34-9bb0-11e4-9cf2-05f0606087d9.png)

What am I missing here?
tested with latest commit 01f7cea94f8f052510ea14e32fb8c1f327a6cdce
Chromium Version 39.0.2171.95 (64-bit)

Ah, I now checked, looks like I reported something like this before here: https://github.com/gorhill/httpswitchboard/issues/404#issuecomment-54061123

**Comment by gorhill** [comment]
It's an XML document. In the console there is:

> Refused to load the script 'http://feeds.arstechnica.com/~d/styles/rss2full.xsl' because it violates the following Content Security

So it appears the browser considers XSL document to be "script", but refuses to even load the these, which means uMatrix won't be aware that a script was requested. Since the document is an XML document, `document.querySelectorAll('script');` return nothing. uMatrix can't know whether there are scripts for this page.

The XML document is parsed and converted to an HTML document by the XSL which the browser refuses to load.

Only solution I can see is to not apply any CSP is the `Content-Type` header does not match to a HTML document.

**Comment by gorhill** [comment]
Looks to me this now works fine in 0.9.0.0.
