### ISSUE TITLE
navigator.platform is exposed despite Spoof User-Agent

### ISSUE THREAD

**Issue by frznvm0** [gorhill/uMatrix#118]
In inspector console:

``` javascript
navigator.platform
// "Linux x86_64"
```

This happens, even though I have "Spoof User-Agent string" enabled on the Privacy tab in uMatrix options.

![Privacy tab](https://cloud.githubusercontent.com/assets/1688398/5949465/40f1c02c-a74e-11e4-970a-39037ca54598.png)

I think the platform should also be a separate option, or maybe parsed from this list.

**Comment by d-kr** [comment]
(I'm just a user, but:) I think that should be (including spoof-agent) in an extra extension, because the complete navigator object tells you much about the browser:

* `.userAgent` returns the user agent too,
*  `.plugins` returns a list of all installed plugins
*  `.appVersion`, `.appCodeName`, `.appName`, `.product`, `.vendor` and many more containing parts of the user agent

and uMatrix is for me "just" for CSP based filtering.

**Comment by frznvm0** [comment]
That's actually a much better idea.
Should I close this?

**Comment by gorhill** [comment]
> Should I close this?

No.

I will not extend the UA-spoofing feature, but I will add the code to try to find the platform and use it, this seems trivial enough to me.
