### ISSUE TITLE
Add a way to whitelist whole domain when only subdomain a present

### ISSUE THREAD

**Issue by yamalight** [gorhill/uMatrix#121]
So, the problem I've been having lately is that a lot of sites are using CDNs like say cloudfront.net for their supplementary js scripts that load comments or similar. Those CDNs usually serve files from several subdomains that look like `d1506sp6x4e9z7.cloudfront.net`. And uMatrix only shows (and as result allows whitelisting) those subdomains since nothing is served from main domain.

The problem here is that I want to easily whitelist all subdomains, like so: `site.com cloudfront.net * allow`. At the moment you cannot do it from GUI, so what I usually do is:

1. Whitelist d1506sp6x4e9z7.cloudfront.net
2. Go to settings -> my rules
3. Find whitelisted subdomain and replace it with top level domain

Which is less than perfect. Would love to have a way to whitelist the top level domain right from GUI without going through all this steps.

P.S. Maybe it's there and I'm just being dumb and not seeing it - in that case please point me towards this feature and close the ticket :)

**Comment by gorhill** [comment]
No there is no way to do it from the matrix. Allowing this would mean to lists all possible TLDs and this would mess up a lot the matrix with noise. Entering manually is the workaround, I don't intend to change this, I want to keep the matrix clean for the majority of users. Instead of whitelisting `d1506sp6x4e9z7.cloudfront.net`, why not just go directly to the rules editor and enter right away `site.com cloudfront.net`, so can skip having to find it.

**Comment by yamalight** [comment]
Well, manual rules creation is not exactly the most user-friendly thing.
Also, I don't think that there's need to list all TLDs, just a way to whitelist the top level would be sufficient as that's the most frequent use case.

I can see two ways to achieve this functionality without changing UI too much:
1. Add floating arrow (similar to the one that's now responsible for collapsing/expanding set of domains) that would trigger a menu with an additional actions, including "white/black-list *.domain.com"
2. If there's only one domain name shown and it's not top-level domain, the name of domain can be split into two smaller columns - one with subdomain symbols and one with top domain address. Using cloudfront example from before: currently `d1506sp6x4e9z7.cloudfront.net | allow | deny | ...`, new way of rendering `d1506sp6x4e9z7 | cloudfront.net | allow | deny | ...`

Both of those will allow making top level interactible without any drastic changes to UI, which would improve UX significantly, IMO.
I can try to make a PR with the proposed changes if you are interested.

**Comment by gorhill** [comment]
> I can try to make a PR with the proposed changes if you are interested

I don't want anything below an effective domain to appear in the matrix. This has been designed this way since the very early versions of HTTPSB. By design.

It's an exceptional case to want to assign a rule to something below an effective domain, and especially it is not something which is advised to do. And I just don't want this kind of exceptional case to make it into the matrix, over-complicating the matrix code which is already rather complex.

**Comment by yamalight** [comment]
Okay, if it's not advised - is there a better way to whitelist CDNs that use multiple subdomains to deliver content from the UI? If not, well, it just makes me really sad. 
I guess I'll just close the issue as well.

**Comment by gorhill** [comment]
> whitelist CDNs that use multiple subdomains

`d1506sp6x4e9z7.cloudfront.net` is not a subdomain, it is an effective domain, as per Mozilla Public Suffix list. The best practice is to whitelist each separately as needed. Asking to whitelist `cloudfront.net` is like asking to whitelist `co.uk`: not advised. You can do it manually in uMatrix, but the matrix UI will not encourage you to do what is not advised.

**Comment by yamalight** [comment]
Hm, I was under impression that some sites change what's preceding `.cloudfront.net `. Looks like it was me being idiot all this time. Thanks for clearing that up for me!
