### ISSUE TITLE
Searching from the URL bar sometimes populates the matrix for Behind-the-scene

### ISSUE THREAD

**Issue by my-password-is-password** [gorhill/uMatrix#128]
1. In the URL bar type in anything with no spaces  and press Enter
2. Look at the matrix for Behind-the-scene

![umatrixbts](https://cloud.githubusercontent.com/assets/6408935/6090598/ab6caa66-ae33-11e4-915c-c039f953998b.png)

It also happens in uBlock.

![ublockbts](https://cloud.githubusercontent.com/assets/6408935/6090600/b7450522-ae33-11e4-9de9-54f656b81858.png)

Don't know if its suppose to work like this.

**Comment by d-kr** [comment]
Do you have any privacy settings enabled? Like "Predict network actions ..."
 etc?

**Comment by my-password-is-password** [comment]
Nope.  Everything under Privacy is unchecked.

**Comment by gorhill** [comment]
The browser sends these net requests.

**Comment by gorhill** [comment]
I can't find the doc, but here is what is happening, as per what I remember from Chromium doc. What you type in the omnibar could be a search term, or the name of a server to which to connect. If the expression is a single word, Chromium will try to use it as a hostname in a network request. This will fail as the DNS fails to lookup the term, in which case Chromium will then treat the term as a search query.

So a net request was fired by Chromium (because single word), and uBlock intercepted that net request and report it, as it is designed to do.

More of a browser behavior than a browser bug really.

**Comment by gorhill** [comment]
Related: <https://github.com/gorhill/httpswitchboard/issues/214>
