### ISSUE TITLE
Matrix does not always open in the right scope

### ISSUE THREAD

**Issue by wfdd** [gorhill/uMatrix#130]
Well, pretty much what it says in the title. For example, though I might've set rules for `www.example.com` and those *do* apply, the matrix will open in `example.com` view, giving me the impression that no custom rules are active. I've been bitten by this a couple of times.

**Comment by gorhill** [comment]
The matrix is supposed to open with the scope selected to the last scope you used. If the last scope was was hostname-level, it is supposed to open at hostname-level. If last to scope was domain-level, it is supposed to open at domain-level.

**Comment by wfdd** [comment]
Does this work across browser sessions? I've found myself in hostname-level scope enough times to know it wasn't my doing.

**Comment by gorhill** [comment]
Yes, across browser sessions. However, keep in mind that even if you are using hostname-level, bringing up the matrix on Github (for example) will select the domain-level (visually), because the hostname happens to match the domain name (`github.com` = `github.com`). However, the level will still be hostname-level, so visiting `http://www.example.com` will set the matrix to `www.example.com`, not `example.com`.

So it comes down to: what was the hostname of the page you visited when you thought uMatrix lost your setting?

**Comment by wfdd** [comment]
> So it comes down to: what was the hostname of the page you visited when you thought uMatrix lost your setting?

Well, the latest one was the Guardian, at www.theguardian.com. Might it have something to do with bare domain redirects?
