### ISSUE TITLE
Suggestions to make µMatrix a real all-in-one addon 

### ISSUE THREAD

**Issue by ThePierrezou** [gorhill/uMatrix#136]
Hello,
I think µMatrix could even be better, especially for those who wish to have a true all-in-one addon which would:
-Provide adblock filtering
-Provide an element picker
-Provide a post-install wizard to guide newcomers
I was loving HTTPSB since it was very close to what I was looking for.
I'd understand if you don't want to do this, but it'd be interesting if someone else'd consider this idea.
Thanks
ThePierrezou

**Comment by Mikey1993** [comment]
https://github.com/gorhill/uBlock

**Comment by ThePierrezou** [comment]
Yeah i know µblock, i use it and i love it but i think a all in one addon.
And i think having a all-in-one addon with the matrix and the adblock filtering is better than having two addon.

**Comment by CrisBRM** [comment]
It's not better, it's less modular. As long as the filter lists don't overlap, it's fine.
uMatrix's learning curve is unreasonable for the average tech illiterate person.

**Comment by gorhill** [comment]
@ThePierrezou 

I don't agree that all-in-one is a virtue in itself. I won't go down that path with uMatrix because I don't think it's a good idea, and anyways I moved _away_ from this (HTTPSB) with uMatrix.

On the other hand, there are other open source projects out there where you could file that feature request: you could ask Adblock Edge to expand itself into an all-in-one by adopting uMatrix UI, or ask Policeman for Firefox to support "adblock filtering". It doesn't have to be me only.
