### ISSUE TITLE
Error in update hostnames

### ISSUE THREAD

**Issue by mikhaelkh** [gorhill/uMatrix#138]
1) Leave only `Malware domains‎`(http://mirror1.malwaredomains.com/files/justdomains) enabled
2) Purge all caches
3) Update now
Now 11,416 distinct blocked hostnames (latest)
4) Restart browser
5) Update now
Now 19,397 distinct blocked hostnames (old)

**Comment by gorhill** [comment]
`Malware domains‎` doesn't update from its home server anymore, the owner of the server had to block requests to download `http://mirror1.malwaredomains.com/files/justdomains`, because of bandwidth cost.

uMatrix now hosts that file, and it will download if and only if there is a new version available.

At step 3), I got 19,397, not 11,416. No mater how much I try, I can't get that "11,416" count.

**Comment by mikhaelkh** [comment]
I have version 0.8.1.3, latest in [Chrome Store](https://chrome.google.com/webstore/detail/%C2%B5matrix/ogfcmafjalglgifnmanfmnieipoejdcf)

**Comment by gorhill** [comment]
Looking at the latest version of that hosts file, it has 11,416 entries. Since uMatrix does not fetch that file from its home server, the only way for uMatrix to show 11,416 entries for that hosts file is because you were using an older version of uMatrix, or because you modified `filter-lists.json` to put back the `homeURL` for that entry. It is just impossible for uMatrix to fetch the latest version of that hosts file from the home server: <https://github.com/gorhill/uMatrix/blob/master/assets/umatrix/hosts-files.json#L8>.

**Comment by gorhill** [comment]
> I have version 0.8.1.3, latest in Chrome Store

Ok I understand. The latest `filter-lists.json` no longer uses `malwaredomains.com` server to fetch the list. However the change is after 0.8.1.3.

**Comment by gorhill** [comment]
I updated all 3rd-party assets, that should resolve the inconsistency.

**Comment by mikhaelkh** [comment]
There are 5 [mirrors](http://www.malwaredomains.com/?page_id=29) of this list. Maybe another server doesn't have bandwidth problems.

**Comment by gorhill** [comment]
Ok, let's see if this causes problem in the future.
