### ISSUE TITLE
[Firefox] Matrix sometimes partially hidden in the logger

### ISSUE THREAD

**Issue by tlu1024** [gorhill/uMatrix#178]
![spiegel1](https://cloud.githubusercontent.com/assets/1099173/7550144/cde470f4-f656-11e4-8d1d-00922ea55b4e.png)

... and unfortunately it's not possible to move/drag it.

**Comment by gorhill** [comment]
Yes, I have a `TODO` item in the code to deal with size. For now collapse the blacklist section and refresh the page, see if this makes the bar accessible. If all fail, go to `about:config`, filter with `umatrix`, and reset the item related to popup position.

**Comment by tlu1024** [comment]
> For now collapse the blacklist section

Thanks, that worked! Feel free to close this issue if you have a respective todo item anyway.

**Comment by gorhill** [comment]
Nah I will fix it today, this is bound to come back again sooner than later. I figure I will save time if I fix it now.

**Comment by castor-troy** [comment]
Also, if it's not too much trouble, can you enable an option to save the log?

**Comment by gorhill** [comment]
Fixed in 486183cbe6d3256c554bbd85b84676089bcab4d2.

I had to remove the ability to move the popup around, this was causing way too many edge issues, and the amount of code to deal with these was no longer justified, especially it was probably still failing in more edge cases.

The popup is not pinned near the top-right corner, and I added a control button to minimize it to get it out of the way to see what is under.
