### ISSUE TITLE
Smart reload when closing uMatrix no longer working

### ISSUE THREAD

**Issue by eproxus** [gorhill/uMatrix#198]

**Comment by gorhill** [comment]
Read the release notes please: <https://github.com/gorhill/uMatrix/releases/tag/0.9.0.0>.

**Comment by eproxus** [comment]
Sorry, my bad. Didn't realize there was an update.

**Comment by mailinglists35** [comment]
this is very annoying, because there is a considerable distance on the screen between chrome reload button and umatrix icon that makes the whole process inconvenient.

the old behaviour was natural, logical and human. 
please bring it back, at any cost.

before: click click click on umatrix, tadaaa

after: click click click... move mouse to the opposite side, click, move mouse back, click, click click, move the mouse again five miles west, click, repeat.

**Comment by gorhill** [comment]
> there is a considerable distance on the screen between chrome reload button and umatrix icon

There is a reload button in the popup.

**Comment by mailinglists35** [comment]
i know, but that is still annoying

**Comment by eproxus** [comment]
@mailinglists35 Since there is a reload button in the popup, your argument is void. It's the same amount of clicks in both the old and new version (since auto reload required a click on the page to trigger). The only difference is that the popup stays open, which allows you to continue filtering until the page works.
