### ISSUE TITLE
uMatrix breaks downthemall in Firefox

### ISSUE THREAD

**Issue by castor-troy** [gorhill/uMatrix#218]
uMatrix breaks downthemall in Firefox, or at least the way I configured uMatrix is not allowing downthemall to download files. I get a server error in the downthemall manager.

Could you help me configure uMatrix to let downthemall download files properly? I could provide any log files or my rules if required.

I tried disabling umatrix and downthemall worked fine. So, I guess its the way uMatrix is configured that is breaking the downloads.

**Comment by gorhill** [comment]
Missing from your issue:

- A nice link for me to install whatever is "downthemall"
- Browser version, uMatrix version
- **Exact, detailed steps** for me to follow so that I can reproduce your issue -- with what should happen versus what is happening

The logger is your best friend, it shows what gets blocked.

**Comment by castor-troy** [comment]
The addon is available at: https://addons.mozilla.org/en-US/firefox/addon/downthemall/

The following are the versions installed in my computer:
DownThemAll 2.0.18
Firefox: 38.0.1
uMatrix: 0.9.0.2

Then, use DownThemAll to download any file. I tried downloading bittorrent Sync, but I get the error for any type of file donwload.
Open the URL: http://filehippo.com/download_bittorrent_sync and click on Download green button on the right of the page. Then use DownThemAll to download.

PS: I am pretty sure it's **not** a problem with uMatrix and it's a configuration error. But I am not able to figure out the right way to configure uMatrix.

![screen1](https://cloud.githubusercontent.com/assets/3329844/7749988/2a30107e-ffef-11e4-89f9-9e769cafbcfa.png)
![screen2](https://cloud.githubusercontent.com/assets/3329844/7749989/2fd5f322-ffef-11e4-90e1-441fcfdda428.png)
![screen3](https://cloud.githubusercontent.com/assets/3329844/7749992/326aeb42-ffef-11e4-8688-b6e250824057.png)

**Comment by gorhill** [comment]
I removed the 3rd screenshot, it contained information which I believed should not be shared.

So I did not try the detailed steps yet, as I believe the solution can be seen in the logger: Notice that DownThemAll tells you that it is downloading something called `211f2b...e5fda4`, and in the logger there is an entry blocked which matches this information:

    http://filehippos.com/download/file/211f2b...e5fda4

You chose to block behind-the-scene network requests (matrix-filtering is disabled by default for the `behind-the-scene` scope), so consequence is that you will need to micro-manage things which breaks because of enabling matrix filtering for the `behind-the-scene` scope.
