### ISSUE TITLE
uMatrix 0.9.1.1 seems to not detect click-to-play as plugin in the matrix/logger (on some pages)

### ISSUE THREAD

**Issue by Blutgang** [gorhill/uMatrix#229]
I've noticed that on `Chrome 42.0.2311.152`, `uMatrix 0.8.1.4` detects the click-to-play (flash) as a plugin on this page (http://kissanime.com/Anime/Detective-Conan/Episode-001?id=12071) and this page (http://www.adobe.com/software/flash/about/). `Chrome 42.0.2311.152`/`Firefox 38.0.1` + `uMatrix 0.9.1.1` does not detect the click-to-play (flash) as a plugin on those pages.

My rules:

```
matrix-off: opera-scheme true
* * * block
* * css allow
* * frame block
* * image allow
github.com github-cloud.s3.amazonaws.com other allow
github.com github-cloud.s3.amazonaws.com xhr allow
github.com github.com * allow
github.com raw.githubusercontent.com xhr allow
github.com render.githubusercontent.com frame allow
github.com render.githubusercontent.com script allow
kissanime.com kissanime.com cookie allow
kissanime.com kissanime.com script allow
kissanime.com kissanime.com xhr allow
```

**Comment by gorhill** [comment]
If you click the click-to-play, is it detected?

**Comment by Blutgang** [comment]
uMatrix (FF) does detect the flash plugin if you do click on the click-to-play. uMatrix (Chrome) on the other hand will show `other` because of that unresolved bug (https://code.google.com/p/chromium/issues/detail?id=410382).

**Comment by Radagast** [comment]
I'm encountering this issue with fx too. I've found if I have flash set to 'Ask to Activate' even with the necessary connections allowed in the matrix, embedded flash will not load. If the flash plug-in is set to 'Always Activate', using the same matrix settings, embedded flash will play.

As an example: https://www.pathofexile.com/forum/view-thread/1281570
With the matrix settings below, with flash on ask, the plug-in fails. with flash on always, the plug-in loads.

![Imgur](http://i.imgur.com/4r9aTEC.jpg)

**Comment by gorhill** [comment]
> with flash on ask, the plug-in fails. with flash on always, the plug-in loads

Expected. The issue here is just one of reporting -- I know why it happens. There was code to report embedded plug-ins before, and I removed this. I lean toward keeping it removed because:

- Removing plug-in detection in content script remove an overhead which is not really needed
- This happens only with click-to-play
- Whether a plug-in exists on a page is reported in the address bar when click-to-play is enabled
- If it is reported in the matrix, a user might be confused as to why the plug-in does not work if it is allowed in the matrix: because it needs to be click-to-played first.

Summary, I believe I will keep the current behavior, it makes sense. For those who are coming to uMatrix for the first time, this won't come out as a surprise that plugins are not reported in the matrix if click-to-play is enabled.

**Comment by gorhill** [comment]
Closing because issue is likely obsolete by now. I can't repro any of the cases provided (no Flash seen on the pages).
