### ISSUE TITLE
It's is really necessary (yet) to deinstall first to update uMatrix in Firefox?

### ISSUE THREAD

**Issue by Alpengreis** [gorhill/uMatrix#235]
**@gorhill**

Is the following (as described on site https://github.com/gorhill/uMatrix/blob/master/doc/README.md) really necessary (yet) for uMatrix in Firefox?

"Although uMatrix is a restartless addon, I found that installing a newer version over an older one often will glitch the installation. These steps always worked fine:"

Even for uBlock (Fx), there is no such suggestion ... and until now, I had NoScript for Firefox and AFAIK, it was NEVER necessary to deinstall first ...

Greetings
_Alpengreis_

**Comment by gorhill** [comment]
I just tried it and it worked fine installing over.

It's just that sometimes if seems there is a glitch somewhere in Firefox and some old stuff from the previous version is not flushed -- maybe it's a cache thing, and this causes uMatrix to not function properly. On my side I have to install often because development, so maybe it's more likely to happen to me.

**Comment by Alpengreis** [comment]
Ok, all right. BTW: I found also for uBlock this recommendation to deinstall first (had not immediately seen). So , to be ALWAYS secure, I make it so from now on for uMatrix/uBlock - not a big thing ...

Thanks!
