### ISSUE TITLE
KB SSL enforcer replacement?

### ISSUE THREAD

**Issue by anarcat** [gorhill/uMatrix#265]
Does the uMatrix extension replace things like [KB SSL enforcer](https://github.com/kbitdk/kbsslenforcer) or [https everywhere](https://www.eff.org/https-everywhere)?

I guess i'm a little confused by the "https traffic only" button...

**Comment by CrisBRM** [comment]
No idea about KB SLL enforcer, but https everywhere cannot be replaced by uMatrix since they are inherently different. uMatrix only blocks (assuming you've toggled that option on) mixed content, whereas https everywhere attempts to rewrite requests to these sites to https (eg: rewrite other people's links so that they are https, instead of http).

**Comment by anarcat** [comment]
that is what kb SSL enforcer tries to do: it redirects you to HTTPS if there's such a version.

so i guess that answers my question ("no"), thanks! :)
