### ISSUE TITLE
Cookie option

### ISSUE THREAD

**Issue by pcause** [gorhill/uMatrix#275]
One thing that would be a valuable addition for me and I assume others would be if we could have an option for cookies where instead of allow/deny we could also have "tab"  as an option.  This would allow the cookie to be set on and kept as long as there was a browser tab open that matched the site rules.  Once the last tab that used the cookie closed the cookie would be deleted.

**Comment by mdln** [comment]
This is really similar to the functionality of temporary whitelisting + 'Delete non-blocked session cookies X minutes after the last time they have been used', though the latter could probably be modified to also check if the tab is open before deleting the cookies.

An alternative would be to outright clean session cookies and etc when the tab is closed, though this functionality can be (jokingly) accomplished by using windows instead of tabs and set Firefox to clear on exit. Chrom* doesn't have this ability iirc, and having different functionality between browsers is something I believe @gorhill is trying to avoid.
