### ISSUE TITLE
[Feature Request] Option for autosaving rules

### ISSUE THREAD

**Issue by nussbaumer** [gorhill/uMatrix#294]
I always forget to save (temporary) changes in the matrix and have to redo them next time. What about an autosave option in the addons' preferences?  
Thanks for the great addon!

**Comment by gorhill** [comment]
You can go in the _My rules_ pane in the dashboard and commit your rules from there.

Auto-saving is not a good idea, the issue will become, "I use auto-saving, but sometimes I forget to erase temporary rules and they end up permanent". The current way of dealing with temporary rules has been true since the early days of HTTPSB, and I do not intend to change this.
