### ISSUE TITLE
Feature request: split iframe/embedded plugins origins

### ISSUE THREAD

**Issue by siavash119** [gorhill/uMatrix#318]
Can we get iframe calls as separate origin settings rather than a call from the top level site?

For example on an ign article: http://www.ign.com/articles/2015/07/23/drug-tests-mandated-by-pro-gaming-league, they load an iframe from disqus.com and the iframe gets from disquscdn.com; it's not a call from ign.com itself, but with the current settings i need to allow from ign.com. Can this be split in the UI and settings? It makes those sites easier to use across websites too (for example i can allow youtube to access ytimg and googlevideos then on any other site i only need to allow access to youtube to get all those settings). I think policeman does a good job of correctly showing origins and destinations if you want to look at his code: https://github.com/futpib/policeman

**Comment by the8472** [comment]
>  It makes those sites easier to use across websites too (for example i can allow youtube to access ytimg and googlevideos then on any other site i only need to allow access to youtube to get all those settings).

It may make sense to have different rules when a site is a top level site and when it's embedded.

For example you might want to allow cookies and various google domains for necessary for login on youtube.com but not allow those when viewing embedded youtube videos on another site because it doesn't add value there.

Or similar, when you want to allow google recaptcha at a particular site (which has a ton of google-related dependencies) doesn't mean you want to apply the "usual" rules you would apply when google.com is your top frame.

**Comment by gorhill** [comment]
If it can't be represented in the matrix, it won't be implemented.People uses uMatrix because of how straightforward to set rules, and the UI is a defining feature of uMatrix, and it's why it has not really changed since even way before HTTP Switchboard became mature. So the matrix UI is there to stay as is, and anything which does not fit naturally in this UI will be rejected -- as this would betray the main reason users prefer uMatrix to other alternatives. Workaround is to use the alternatives.

**Comment by the8472** [comment]
The specific `<iframe>` case could be represented in the matrix by a bubble folding out from the rule allowing the frame embed itself.

I.e. you allow the frame embed. And then inside the frame you allow certain requests without allowing them in the top window context.

![bubble](http://i.imgur.com/opQXMXX.jpg)

This would preserve the table structure of the matrix while signalling that some rules are scoped to specific subframe.

**Comment by the8472** [comment]
If the `<iframe>` has the appropriate `referrer` and `sandbox` attributes set it might make even more sense to give them special treatment since they essentially act like a separate tab that does not leak cross-origin information to the embedded content.

That way one could allow safe 3rd-party content embedding while still blocking everything else.
