### ISSUE TITLE
erroneous blocking

### ISSUE THREAD

**Issue by grrrrr** [gorhill/uMatrix#329]
When I go to http://piwik.org/ or any of it's pages  I am getting blocked by uMatrix 

> uMatrix has prevented the following page from loading:
> http://piwik.org/

And only the option to close.    Is there any way to see why this is getting blocked and how to prevent it, I assume given the nature of the site it is problematic for others too.  I am sure it affects others too.

This is running on
* uMatrix 0.9.2.1
* Firefox 40.0
* Ubuntu 14.04

**Comment by gorhill** [comment]
uMtrix does not block erroneously, it blocks what it is told to block.

`piwik.org` is in MVPS, so you need to contact MVPS' maintainers. Unblock using the matrix or create local or global rule to unblock as you wish.

**Comment by rafis** [comment]
The problem it does not have button to temporary unblock. Just blocked and f*ck you.

**Comment by muellert** [comment]
I don't know where to adjust this, but I can't click on some ads on taobao.com. The result is this error message, with
https://click.simba.taobao.com/cc_im?p=%C...
I would like to not completely disable ublock on this site, however. I have Firefox 46.0.1 on Linux.

**Comment by rubypanther** [comment]
Pretty lame to see this closed as "we don't make mistakes" when there is a clear problem with being able to conveniently turn off blocking under user control. Users don't care how you classify it, if you see it as a bug, misfeature, feature request, etc. Different developers have different opinions on that. But clearly it is something that is problematic for users, because there is no button like "I understand, continue anyways."

**Comment by toshiya44** [comment]
Doesn't sound like you actually use uMatrix @rubypanther 
First line in README.md is `Definitely for advanced users.`. If you're using uMatrix you're expected to be able to unbreak websites on your own.
