### ISSUE TITLE
Open uMatrix when hovering over toolbar icon

### ISSUE THREAD

**Issue by dllud** [gorhill/uMatrix#336]
It would be great if uMatrix opened when hovering over its toolbar icon and then closed when the mouse pointer got out of the matrix area. Check [NoScript](https://noscript.net/) for a working example. This simple functionality would spare us lots of clicks by the end of the day.

**Comment by vdcbb** [comment]
This was always one of the first things I disabled in NoScript. Drives me nuts when simply moving your mouse over something starts causing popups on the screen. The current state of websites often leaves me unable to read content because where ever I move my mouse something is popping open.

If one click is too much effort for you (and you use Chrome), you can assign a keyboard shortcut to open the matrix. You can find the option at the bottom of the extensions page. Unfortunately, there is no keyboard shortcut option in Firefox.

**Comment by dllud** [comment]
I'm using Firefox. Though the keyboard shortcut would not solve my issue. I would still have to move my mouse to the matrix in order to operate it. Or are there any special keyboard shortcuts for this?

**Comment by tarbucktransom** [comment]
Seconding this. Specifically, I want there to be an option (disabled by default) for mousing over the uMatrix icon to open the matrix, and then reload the page on mouseout only if there were any changes made. With the option enabled, clicking on the uMatrix icon would leave it on until the icon were clicked again regardless of mouseout or switching windows.

**Comment by gorhill** [comment]
I am no longer maintaining the Firefox legacy version.
