### ISSUE TITLE
Please mention popup redirect blocking feature

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uMatrix#364]
@gorhill Please read this post: https://forums.lanik.us/viewtopic.php?f=62&t=22848&p=77697

It explains uMatrix as the only known blocker that can block pop-up/pop under redirects.

Can you please mention this in https://addons.mozilla.org/en-us/firefox/addon/umatrix/ and in https://github.com/gorhill/uMatrix/blob/master/README.md ?

**Comment by gorhill** [comment]
I tried the test case, clicking on the logo "PornHub" at the top left of `www.pornhub.com`, and uMatrix/uBlock Origin did block a redirect to `ebocornac.com` through their respective strict blocking implementation, but they did not prevent the pop-under from occurring.

So mainly it's strict blocking at work. In the current case, even if the pop-under occurs, strict blocking will prevent the pop-under from loading any content, because `ebocornac.com` is listed in Peter Lowe's list, which is enabled by default in uBlock Origin.

**Comment by flyingzebras** [comment]
Thank you. I updated the post about this.
