### ISSUE TITLE
[Request] Either allow CDNs automatically or support wildcards in hostnames or both

### ISSUE THREAD

**Issue by ParticleMon** [gorhill/uMatrix#367]
As many sites use a CDN to load, not to mention function, properly, seem to be used only for 1st-party content, and whose names are typically quite obvious (*cdn*.*, as in a regex *, matching 0+ chars) should work for the vast majority), how about uMatrix (and uBlock) either:

1. Automatically detect and allow CDNs
2. Support wildcards in rules

Or perhaps there is a better way?

**Comment by vzjrz** [comment]
Whitelisting all `cdn.*` matches seems a little unsafe. Why not just whitelist cdn you know and trust like `* ajax.googleapis.com script allow`.

**Comment by mooglestiltzkin** [comment]
whats so hard about manually one blocking CDN, then just do global for the CDN. (all other elements for 1st party site can be kept for local only. The only thing global is that CDN, which may be used for other sites as well). Problem solved....

**Comment by gorhill** [comment]
uMatrix is a hard blocker, meaning it won't try to automatically whitelist stuff without user intervention.

Wildcard in rules are not supported because of efficiency: the core engine is efficient and I don't plan to depart from this for the sake of edgy features.

**Comment by ryanbnl** [comment]
@gorhill , I think that you should reopen this. adding support for wildcards would make uMatrix better. For example, Coursera use cloudfront and the urls use a random subdomain (xys.cloudfront.net). With the current uMatrix it's not possible to allow *.cloudfront.net on coursera.com.

For Coursera there are workaround, but for some sites there aren't - some sites appear to generate totally random subdomains on a per-request basis..

I don't want to globally allow cloudfront.net - because I don't know what other sites are including on it.

**Comment by berrythesoftwarecodeprogrammar** [comment]
are you sure they have dynamic random subdomains? in my experience, websites which use cloudfront usually only have 1-3 randomized static subdomains and whitelisting those individually the first time is enough. you could also go into the umatrix settings and add a rule manually for it since it wont be available in the popup

`coursera.com cloudfront.net * allow`

**Comment by ryanbnl** [comment]
With coursera there are just lots of them,  more appropriate are each week
as new videos are added. So not random,  but it is annoying.
I'm open to making a fix,  but only if there's a chance my PR would be
accepted..

**Comment by berrythesoftwarecodeprogrammar** [comment]
i dont think it will be. (sub)domains are displayed in umatrix based on the public suffix list and gorhill wont change that. whats so hard about adding a rule in manually? that would fix coursera and cloudfront issues for good

**Comment by ryanbnl** [comment]
I tried adding a wildcard rule but that didn't work. Which is why I'm
suggesting it :) All you need to do is support, say, * as wildcard for a
rule and you're there. No UI changes, and hopefully a one-liner :)

**Comment by berrythesoftwarecodeprogrammar** [comment]
`coursera.com cloudfront.net * allow`
this is it. it allows every subdomain on cloudfront.net. you dont need  a wildcard symbol

**Comment by gorhill** [comment]
>  a random subdomain (xys.cloudfront.net)

It is random-_looking_, but it's not random.

**Comment by ryanbnl** [comment]
Thanks @berrythesoftwarecodeprogrammar, that worked like a charm.

Sorry for dragging the discussion up, I don't like wasting fellow developer's time (I hate it myself).

@gorhill,

You're right - or course it's not totally random - it'll be generated by some algorithm, probably as part of some partitioning/multi-tenant support. That the distinction doesn't really matter for my request :)

There still remains an edge-case for sites which include content from a range of IP, which are "randomly" chosen. But I only have one example (a certain streaming site) and it's not worth burdening the core engine with the overhead of regexes just to gain support for an extremely rare case. Then using AdBlock in a 2nd browser is the solution.

**Comment by berrythesoftwarecodeprogrammar** [comment]
@ryanbnl u can do this, see #122 .
e.g. 
```videosite.com 98.12.43 other allow
videosite.com 97.43 other allow
videosite.com 121 other allow```

**Comment by ryanbnl** [comment]
wow, that's fantastic. thanks @berrythesoftwarecodeprogrammar, I really appreciate the help :)
