### ISSUE TITLE
Behind the scene logger not picking up content types which uBlock does

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [gorhill/uMatrix#371]
sorry if this is related to any other issue, but i couldn't find anything exactly like this or any information about it. my uBlock behind-the-scene logger picks up things such as 'websocket', 'media' etc but my uMatrix does not. is that intended behaviour?

also kind of unrelated: i've been using uBlock and uMatrix together successfully for a while now. i just try to keep host files and dynamic filter rules on umatrix and everything else on ublock. does either ublock or umatrix take precedence over the other? would blocking certain behind-the-scene requests work better in one addon more than the other? (i guess thats kind of related if umatrix does in fact not support blocking certain content ublock can)

thanks

**Comment by 5t3f4n** [comment]
uMatrix can block all types of media as well as far as I'm aware, the difference is that uMatrix categorize them as `other` instead of `media`. Open both request loggers and compare, look for the item and you should hopefully see it in both albeit under different types.

There used to be a merit to having uMatrix handle malware domains and such, since uBlock Origin would still load the root document. But since uBlock Origin introduced strict blocking, this is no longer the case as is explained in [this page](https://github.com/gorhill/uMatrix/wiki/Using-uBlock-with-uMatrix). The recommendation seems to be to leave malware domains in **both** uMatrix and uBlock Origin, but this page is need of an update so take it with a grain of salt.

**Comment by berrythesoftwarecodeprogrammar** [comment]
yeah. but for the websockets and media which i encountered yesterday, they didnt appear in the umatrix logger at all! not even as 'other'

**Comment by gorhill** [comment]
> my uBlock behind-the-scene logger picks up things such as 'websocket', 'media' etc but my uMatrix does not.

URL?
Browser/version?

**Comment by berrythesoftwarecodeprogrammar** [comment]
oh sorry.  Firefox 40.0.3. the websockets were from github being open

**Comment by 5t3f4n** [comment]
>URL?
Browser/version?

I don't know any example of `websocket` but you I can give STR for a `media` one.
* Go to https://boards.4chan.org/wsg/catalog. *
* Open any thread that contains at least one .webm video.
* Click to play the .webm video "in-line" with the page.
* You now have an `other` in uMatrix and a `media` in uBlock Origin for the same .webm video.

`uMatrix 0.9.2.1`
`uBlock Origin 1.2.0`
`Firefox 41.0.1`
`OS X 10.11 (15A284)`

\* Keep in mind that although this is the *Worksafe GIF* board, 4chan is still 4chan.

**Comment by berrythesoftwarecodeprogrammar** [comment]
hmm i dont get the same behaviour as you @5t3f4n 

![ublock](https://my.mixtape.moe/idubco.png)
![umatrix](https://my.mixtape.moe/thavub.png)

**Comment by 5t3f4n** [comment]
That's odd. uMatrix doesn't even have a cell for media so I can't imagine what else it would fall under.
Here are some screenshots of what I mean:
[uMatrix](https://i.imgur.com/951rH5b.png) showing `other`.
[uBlock Origin](https://i.imgur.com/YiTNqn1.png) showing `media`.

But I feel I've taken this slightly off topic now because the biggest issue here is requests not appearing at all, not being categorized differently, which I cannot reproduce.

I'm seeing a `websocket` in uBlock Origin from `live.github.com/_sockets/[…]` and that same URL is showing up in uMatrix as `other`.

**Comment by berrythesoftwarecodeprogrammar** [comment]
ok yeah they show up in umatrix logger only in the All tab

**Comment by berrythesoftwarecodeprogrammar** [comment]
so @gorhill , i just remembered about this issue and checked again, here are my results on Firefox 43.0.4 with the latest uMatrix and uBlock versions, for github websockets (`https://live.github.com/_sockets/*`):

uMatrix:  
sees the source as: `github.com`  
thinks the content is: `other`

uBlock:  
sees the source as: `behind-the-scene`
thinks the content is: `websocket`

screenshots:  

umatrix:
![umatrixsocket](https://cloud.githubusercontent.com/assets/6548571/13635740/e27da8f0-e651-11e5-8090-9e2edba8505c.png)

ublock:
![ublocksocket](https://cloud.githubusercontent.com/assets/6548571/13635745/e69308b8-e651-11e5-901b-1f5bcc49a08b.png)

so not only do the content types differ, the source does too

**Comment by gorhill** [comment]
uBO and uMatrix are two different extensions, they report differently. uMatrix does not know about `websocket` so it's reported as `other`.

**Comment by gorhill** [comment]
Hmm, on the other hand I would not expect the requests to be in different scopes -- if uMatrix is able to resolve the request to the proper scope, I would expect uBO to be able to do the same.

**Comment by berrythesoftwarecodeprogrammar** [comment]
yeah thats the main problem. should i close this and open it on the ublock github?

**Comment by gorhill** [comment]
> should i close this and open it on the ublock github?

Yes, thanks. Will look into this asap.
