### ISSUE TITLE
uMatrix incorrectly categorizing and blocking content types

### ISSUE THREAD

**Issue by the-nothingman** [gorhill/uMatrix#390]
Something has changed in the most recent Nightly (44.0a1 2015-10-20) that causes uMatrix to recognize images and CSS type content (possibly other scripts too but I'm not sure yet) as other type and thus block it. Its breaking many sites and make uMatrix difficult to useless on many sites. 

![2015-10-20](https://cloud.githubusercontent.com/assets/7260835/10620294/3b7b6da8-7748-11e5-8aef-d39dfaf3ce0e.png)

**Comment by Niamor** [comment]
I can confirmed this, same thing for me

**Comment by gorhill** [comment]
My Nightly is from 2015-10-18, I will see when I receive 2015-10-20.

**Comment by gorhill** [comment]
Does uBlock Origin categorize properly?

**Comment by gorhill** [comment]
This is probably [code at line 1831 of `vapi-background.js`](https://github.com/gorhill/uMatrix/blob/master/platform/firefox/vapi-background.js#L1831) which behaves unexpectedly:

    rawType = channel.loadInfo && channel.loadInfo.contentPolicyType || 1;

So apparently in latest Nightly, `channel.loadInfo` or `channel.loadInfo.contentPolicyType` is nil.

**Comment by the-nothingman** [comment]
its still blocking ads properly but I also don't use Dynamic filtering since i use uMatrix

**Comment by gorhill** [comment]
The logger will tell you whether uBO categorize properly. There is a column for the request tye.

**Comment by the-nothingman** [comment]
ok double checked uBO and its working as intended

**Comment by gorhill** [comment]
I can't test but I expect [0.9.3.0rc2](https://github.com/gorhill/uMatrix/releases/tag/0.9.3.0rc2) to fix the issue. (Of course I did test uMatrix still work fine on Nightly and Pale Moon, so everything in between should work fine as well).

**Comment by Niamor** [comment]
It works as intended now, thank you.

**Comment by Niamor** [comment]
Hello, sorry to bring this back up but it looks like the issue is not entirely fixed.
images from other extensions show as other. Browsing Reddit with RES. I don't have any other extensions that changes content of a page so can't test more.
Works fine on ublock origin.

![umatrix_log_-_nightly_2015-10-21_17-47-59](https://cloud.githubusercontent.com/assets/30397/10642251/0d811904-781d-11e5-9bb9-608a558698bc.png)

![ublock _ _network_request_log_-_nightly_2015-10-21_17-48-17](https://cloud.githubusercontent.com/assets/30397/10642245/06f4f27c-781d-11e5-8edd-e71c6375321d.png)

**Comment by gorhill** [comment]
I see two resources with the same URL in the uMatrix screenshot, one blocked (`other`), one not blocked (`image`). If you uMatrix and uBO were enabled at the same time, it's normal for uBO to not see the request blocked by uMatrix (on FF at least). If you disable uMatrix, I expect you will also get the same as with uMatrix.

**Comment by Niamor** [comment]
Oh I didn't even see that there was two with the same url.
It indeed also shows as other in behind the scene in uBO.
It doesn't show the image though even if apparently according to the log the image is blocked then allowed, I don't really understand. What exactly is other?
Thank you.

**Comment by the8472** [comment]
this fix introduces sync messages in e10s, which are detrimental to performance. 

The [old code using loadinfo](https://github.com/gorhill/uMatrix/commit/6c0c62cc139281bcda237fd5041f23bd54945573#diff-8334c71c60f201b518259aad4d0bddd8L1831) should be fine if you use feature-detection to check if `loadInfo.externalContentPolicyType` is present instead of `.contentPolicyType`

see https://bugzilla.mozilla.org/show_bug.cgi?id=1182571

**Comment by gorhill** [comment]
> feature-detection to check if `loadInfo.externalContentPolicyType` is present instead of `.contentPolicyType`

Tell me if I get this right. As I understand your suggestion now, the feature-detection part would be a bit not-straightforward:

the HTTP observer would detect whether `loadInfo.externalContentPolicyType` is available, and if so would tell the content-side module (`frameModule.js`) through a special message that there is no need to fire sync messages, in which case the content-side module would re-configure itself to no longer fire sync messages.

Or is there another way?

**Comment by the8472** [comment]
I think something like `loadInfo.externalContentPolicyType !== undefined ? loadInfo.externalContentPolicyType :  loadInfo.contentPolicyType` should do the job in all current firefox versions. So the frameModule can just use the same check as before (version < 35) and never run in modern browsers.

Basically restoring the old behavior and just probing under which name the property is available.
