### ISSUE TITLE
Updated to master HEAD (15dc2dc) lost all my configs

### ISSUE THREAD

**Issue by number5** [gorhill/uMatrix#406]
**Expected**: upgrade uMatrix with my configs keep in tact

**Actually happened**: Configs reset to default after upgrade to 0.9.3.1 (15dc2dc)

**Steps to reproduce**:
  -  Install older version of uMatrix and make some changes to configs and rules
  -  
```
git clone https://github.com/gorhill/uMatrix.git
cd uMatrix
./tools/make-clean.sh 
./tools/make-chromium.sh
```
  - Install following the [manual install instruction](../blob/master/doc/README.md#chromium) 

I had been using this method to upgrade uMatrix (and before that uBlock) for few weeks now, this is the first time it reset the config.  I can't get back the rules uploaded to the cloud either. But luckily I had a backup of last week.

**Comment by gorhill** [comment]
You're not giving any details about your browser/version.

**Comment by number5** [comment]
Sorry, missed the important bits:

```
Google Chrome	46.0.2490.80 (Official Build) (64-bit)
Revision	c6bfd1395b9449cb59180d45944a8cb56799bd9c-refs/branch-heads/2490@{#549}
OS	Mac OS X 10.11.2
Blink 	537.36 (@c6bfd1395b9449cb59180d45944a8cb56799bd9c)
JavaScript	V8 4.6.85.28
```

**Comment by gorhill** [comment]
If your settings were reset, it's because:

- You install in a different path.
- You uninstall uBlock prior to install.
- You removed/reinstalled the browser.

I never had this problem occur before, and this was never reported, so something occurred on your side which you will need to investigate -- like try to reproduce if you think uBO did something wrong.

**Comment by gorhill** [comment]
By the way, if the cause is because you install in a different path (let's say you executed `git clone ...` in another place than usual), your settings are not lost: just be sure to call `git clone ...` from the usual location and restart the browser, all your settings will be back. It's the most likely mistake.

**Comment by number5** [comment]
I'm not doing `git clone` each time, just `git pull`

But I **do** move the parent directory to elsewhere and use symlink to keep the path, i.e. physical location changed from `/Users/bruce/src/git/uMatrix/dist/build/uMatrix.chromium` to /Volumes/Data/home/src/git/uMatrix/dist/build/uMatrix.chromium`

So uMatrix use the extension path as a key to store my data?

**Comment by gorhill** [comment]
> So uMatrix use the extension path as a key to store my data?

It's Chromium/Chrome. I don't know the internal details, but by the look of it the full path is used to generate to generated unique id for locally installed extensions. So different full path = different extension id = different local storage. If you reuse the old full path, all your settings will be back -- at least I found it works in the short term.

**Comment by number5** [comment]
@gorhill that make sense :) feel free to close this ticket.

And thanks for all the hard works, I really like uMatrix/uBlock
