### ISSUE TITLE
Cloud storage sync only uploading

### ISSUE THREAD

**Issue by Kaganis** [gorhill/uMatrix#420]
Using uMatrix with the latest stable Chrome on several devices.  After enabling cloud sync on all of them, and uploading my rules from one of them, none of the other devices have pulled down the uploaded rules or other settings.  Nor am I seeing an option to force them to manually.  It's possible I'm doing something wrong here, so a quick walk through of how it should work is probably the first step.  Thanks!

**Comment by gorhill** [comment]
How did you install uMatrix?

**Comment by Kaganis** [comment]
Via the Chrome extension store.

**Comment by gorhill** [comment]
> a quick walk through of how it should work is probably the first step

uBO's doc applies: <https://github.com/gorhill/uBlock/wiki/Cloud-storage>, except that for uMatrix, only the _My rules_ is cloud storage-aware.

**Comment by Kaganis** [comment]
Thanks for that!  Helps narrow down the problem somewhat.  It's actually a problem where the first device wouldn't upload the rules.  Going to try some more troubleshooting (_might_ be hitting the chrome sync size limit mentioned).  Feel free to close this - if it's still a uMatrix problem I'll open a new issue with the pertinent info.  Thanks again!

**Comment by meradz** [comment]
There are a lot of scripts and XHR connections when using quickconnect as it attempts various ipv4 and ipv6 connections using both private and public addresses. You can try watching the logger and add allow rules as needed. As a test, try connecting directly to NAS instead of using quickconnect. Example:
https://192.168.1.250.:5001
http://192.168.1.250:5000
