### ISSUE TITLE
[QUESTION] Filters lists for and/or from uBlock Origin in uMatrix.

### ISSUE THREAD

**Issue by Piter432** [gorhill/uMatrix#443]
Hello. I'm not reporting a bug or issue with uMatrix, but I have a question, which i want to start here.

Anyway, in uBlock Origin anyone can have as many filters lists as user wants (unless the browser or computer can't hold that 😜), but are this filters lists work in uMatrix? Or to be more specific – are they recommended for uMatrix, I mean they won't freeze browser or this extension or crash one or both of them? I mean about those filters lists, which are not both available by default and selected by default in uMatrix and uBlock Origin, but are available by default and/or selected by default only in uBlock Origin?

Question can be complicated, because I know how to write this question, but in Polish, not in English :/

**Comment by ldgbc** [comment]
No.
uBlock can use "picture / image / CSS / layout" or "URL / link" filters to block everything you want.
UMatrix use "host / domain / website / URL (1st level)" to block thing. 

For example: You can make uMatrix block "https://github.com" but you can't make it block just this page: https://github.com/gorhill/uMatrix/issues/443

**Comment by berrythesoftwarecodeprogrammar** [comment]
look at the lists. the ones which are just lists of hostnames are hosts files which can be used in umatrix.

i think somewhere in the wiki of either addon, gorhill talked about the usefulness of having the same hosts files enabled in both ublock and umatrix. i personally disabled the hosts files in ublock and put them into umatrix and use ublock only for other filters

**Comment by kousu** [comment]
This is my question too: Mozilla featured uMatrix this month, after I just installed uBlock two months ago and now I'm confused. It's not clear to me if they are complimentary or redundant.

What is the grand design here? [@gorhill wrote](https://github.com/gorhill/uMatrix/wiki/Changes-from-HTTP-Switchboard) that uBlock and uMatrix are forks of different aspects in HTTP Switchboard. Then [this suggests that they are complimentary](https://github.com/gorhill/uMatrix/wiki/Using-uBlock-with-uMatrix), but @gorhill has written at the top of it that it's out of date. uMatrix has the hosts file tab, which includes some of the same filter lists as uBlock. I would rather not use both if I don't need to, but I don't understand why they were split in the first place.

I tried to get all my friends and even my Mom to use NoScript in the past. It didn't take because the startup cost with NoScript is too hard: too much to learn about network infrastructure and too many buttons to click in the way of just reading the news or buying crap on eBay. Ghostery's UI went over better, but u* are more attractive because they're fully FOSS I would like to start recommending it/them but I want to understand what I'm supposed to be recommending.

**Comment by gorhill** [comment]
.> are this filters lists work in uMatrix

No, uMatrix can only process hostname-based filters/HOSTS file.

**Comment by kousu** [comment]
Then should we be installing both uBlock and uMatrix simultaneously?

**Comment by gorhill** [comment]
I don't tell people what to install -- it's for them to decide according to what they are trying to achieve.

**Comment by kousu** [comment]
We are asking for advice.  You have four blocking projects with overlapping and partially out of date wikis and it is not clear where each fits in. People can't formulate what they want without understanding what can be achieved. 



Does uBlock completely replace AdBlock and Ghostery (are those essentially blacklists with different themes? And unlock subsumes both themes)?  What about HTTPS Everywhere or HTTP Nowhere? Or the various cookie management extensions?   Especially, is it redundant to install uBlock if I have uMatrix?  uBlock looks to me like an easier uMatrix, but some of the snippets I've read hint that they have different goals entirely. The trouble is I can't figure out how to describe those goals to myself.

Please, I'm just confused.

**Comment by adrienbeau** [comment]
> We are asking for advice.

Advice is not easily given, and easily misleading. Giving proper advice takes a lot of time.

>  You have four blocking projects

As far as I know, there are only two actively maintained: uBlock (the most popular by far) and uMatrix.

> (lots of questions about lots of extensions)

I think you should find a forum where such topics are discussed among enthusiasts, and ask there. This tracker is to report issues in uMatrix.

> is it redundant to install uBlock if I have uMatrix?

uMatrix blocks and alters outgoing HTTP requests, while uBlock blocks and alters individual elements in web pages. Both can block requests to a blacklisted host, so they are redundant in that case. uBlock can do more (block individual elements in a page), so that part is not redundant. Maybe uMatrix also has a few features that uBlock doesn't have? I don't use uBlock so I don't know.

It seems to me uBlock is more end-user friendly (just enable big filter lists, and be protected), while uMatrix is more of a "do-it-yourself" extension (I have actually removed all uMatrix blacklists, and created a small one of my own). It is also likely that uBlock consumes more resources (RAM, CPU) than uMatrix, but I don't know it is an issue in practice, especially compared to AdBlock and the like, which are notorious resources hogs.

You mentioned your Mom having difficulty with NoScript. Don't install uMatrix for her.
