### ISSUE TITLE
Content Window doesn't show until after F11 is cycled

### ISSUE THREAD

**Issue by vdcbb** [gorhill/uMatrix#447]
This is reproducible on both Firefox & Chrome:
1) go to webpage (I did so in Private Browsing so cookies etc were clean): http://www.icebreaker.com/en/web-specials/merinoloft-helix-reversible-shirt/102666_WS.html?dwvar_102666__WS_color=301

2) Allow all elements for "icebreaker.com" and "edgesuite.net" and then refresh the page. In my tests I had elements for all other domains blocked.

2) scroll down the page to where it says "Fit: Regular" and click the orange colored "?" that is inside a circle. The screen will dim black but no "content" is shown.

3) press F11 so that the Firefox window maximizes. Press F11 again so that it unmaximizes. 

4) click anywhere on the screen to get back to the normal looking webpage.

5) click the "?" that is inside the circle again. 

6) note that a Content Window now appears.

I am submitting this as a potential bug in uMatrix because this issue does NOT manifest when I have uMatrix disabled.

EDIT: Firefox 43.0 with Ubuntu and uMatrix 0.9.3.1

**Comment by gorhill** [comment]
> 2) Allow all elements for "icebreaker.com" and "edgesuite.net" and then refresh the page. In my tests I had elements for all other domains blocked.
> ...
> I am submitting this as a potential bug in uMatrix because this issue does NOT manifest when I have uMatrix disabled.

Wouldn't it be more reasonable to first assume whatever else is still blocked on the page is causing the issue?

**Comment by vdcbb** [comment]
Well, I don't quite follow you because if some blocked element on the page is blocking the content, then why am I able to get the content to appear by simply cycling F11? Cycling F11 does not change the on/off status of any of the uMatrix controlled elements on the page. Stated another way: if I assume that whatever else is still blocked on the page is causing the issue, then nothing should change (i.e., the content should stay hidden) absent my enabling the stuff that is still blocked on the page. Yet this is not the case.

I have all eight "Privacy" settings (e.g., Delete Blocked Cookies, etc) disabled. 

If I'm missing something, I apologize. I greatly appreciate your apps and only want to bring this to your attention if it's something you have time/interest in looking at. If not, then no problem.

**Comment by gorhill** [comment]
> some blocked element on the page is blocking the content, then why am I able to get the content to appear by simply cycling F11?

The content was not blocked, the script on the page crapped because it is not prepared to deal with unforeseen events such as some 3rd-party scripts not being loaded. The modal box was in the DOM, just at a position outside the viewport. There were js errors in the console.

    icebreaker.com baynote.net script allow
    icebreaker.com facebook.net script allow
    icebreaker.com google.com script allow
    icebreaker.com twitter.com script allow

It was not too difficult to see that uMatrix itself was not the issue, I just set **one single** `allow` rule for all scripts with one click (internally `icebreaker.com * script allow`), and the modal box displayed fine. So from there it was a matter of identifying which scripts specifically.

Going from blocking almost everything to disable completely uMatrix without checking anything in between and conclude that there is something wrong with uMatrix is not a good way to use uMatrix, it's essentially putting the burden on me to figure whatever mix of rules unbreak the page. Next time try to allow incrementally until it unbreaks. Also just one click on the `all` cell would have confirmed the page required unblocking more resources.

http://jlongster.com/Starters-and-Maintainers

**Comment by vdcbb** [comment]
Going from blocking almost everything to disable completely uMatrix without checking anything in between and conclude that there is something wrong with uMatrix is not a good way to use uMatrix, it's essentially putting the burden on me to figure whatever mix of rules unbreaks the page.

In my own defense this is not what I did. I just rechecked the site and the "content window" still does not display after I allow "ALL" in uMatrix. Yet when I turn off uMatrix then is works. So my posting was not impetuous and without considerable effort and testing on my part to identify a setting conflict.

The only errors I'm seeing in the Browser Console is "ReferenceError: twttr is not defined" and "ReferenceError: FB is not defined" and "ReferenceError: _bta is not defined" and "NetworkError: a network error occurred". I still do not see how those are indicating a javascript error.
