### ISSUE TITLE
matrix-off globally

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uMatrix#465]
I think it is annoying to click on the power button for each site to see everything as expected when I do not use uMatrix. Occasionally I only need to block plugins from a couple of sites.

How do I set matrix-off for all websites in ```My rules```

**Comment by vzjrz** [comment]
What you're looking for is default-allow mode. Choose one of these settings:
* This will completely turn off umatrix everywhere: `matrix-off: * true`
* This will allow everything everywhere but still block stuff in the host lists: `* * * allow` (<-- this is probably your best option)

All these setting can be applied in the UI by changing the scope to `*` (so that the rules will apply to everysite) and then either: clicking the power button to turn off umatrix then save, or clicking the `all` cell to turn it green then save.

**Comment by flyingzebras** [comment]
@vzjrz What is my best option if I use uBlock Origin in addition?

**Comment by flyingzebras** [comment]
@gorhill I suggest that you add buttons that add these default-allow modes and explain what they do. What do you think?

**Comment by vzjrz** [comment]
It wouldn't make a difference if you also use ublock but I wouldn't use ublock's advance mode (dynamic filtering) since umatrix is basically super-advance-mode. I wouldn't personally use umatrix they way you want to use it but if you **really** need to set umatrix to default-allow I would just set `1st-party` to green instead of `all` in the above rule. It really depends how much trust and privacy you want.
https://github.com/gorhill/httpswitchboard/wiki/How-to-use-HTTP-Switchboard:-Two-opposing-views

**Comment by flyingzebras** [comment]
@vzjrz ```* * * allow``` did it. Thank you very much.
