### ISSUE TITLE
Bypass redirects

### ISSUE THREAD

**Issue by ghost** [gorhill/uMatrix#502]
I encounter sometimes some kind of redirects which are blocked by uMatrix. Here an [example](http://beste-apps.chip.de/android/app/spiegel-online-android-app,de.spiegel.android.app.spon/):

If you click the button "App installieren" uMatrix blocks the request `http://api.smartredirect.de/api_v2/ClickGate.php?p=Z5CZZT9icW&k=b76e223ab6fa4cbb561dd49714eb57ec&url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dde.spiegel.android.app.spon&s=buDL-ba-extDL`

Could it possible that uMatrix strips the right URL out of this and open it automatically?

Another example were such a bypass would be useful is the search provider "Disconnect Search" where you get google results without to use google itself. But if you searching for images you will directly redirected to google, here an example:
`https://www.google.com/imgres?imgurl=https://s3.amazonaws.com/images.disconnect.me/images/protect-li-1.png&imgrefurl=https://disconnect.me/search&h=240&w=240&tbnid=B-55Q1K-hCipOM:&docid=StmoVT7f1scLlM&ei=JHrNVomTMIvs-QH-rYToBw&tbm=isch`
imgurl is the picture, imgrefurl is the visited site with the picture.

Or google itself tracks the user every time you clicking on the search results:
`https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiwpdqLjpDLAhXCXw8KHdxsAykQFggjMAA&url=https%3A%2F%2Fwww.test.de%2F&usg=AFQjCNE6ZMWYHbspL38_McKbUiTMwHL-0A&bvm=bv.114733917,d. ZWU`

It would be very nice if uMatrix could counteract in some way this tracking.

**Comment by gorhill** [comment]
I should just import uBlock Origin's code for handling the parsing of the URL parameters. I won't ever implement automatic skipping, because that is too arbitrary, but at least users will be able to click themselves on whatever they think is the real destination URL in the parse parameters (if any).

**Comment by foresto** [comment]
+1

In fact, I came here to write up a feature request for this very thing. I'm glad someone beat me to it.

This situation comes up many times per day for me, because there are now so many sites that use track-and-redirect URLs instead of directly linking to the URL that the user intends to reach. I'm glad that uMatrix intercepts the trackers, but the fact that it currently just blocks me from reaching my destination is pretty frustrating, especially when the final target URL is readily available, embedded in the query parameters of the blocked URL. My current solution is to copy the blocked URL, navigate to a URL decoder site, paste the copied URL, run the decoder, highlight the part that is link that I wanted in the first place, and copy it back into my browser. Sometimes I'm just too tired for that nonsense. Result: uMatrix is effectively denying service when it could instead be helping me.

Here's yet another example from just a few minutes ago:

    uMatrix has prevented the following page from loading:
    http://www.tkqlhce.com/click-552179-10728762?SID=ASDFWECDSDR2d0FBQUJ&URL=http%3A%2F%2Fwww.columbia.com%2Fmens-northern-pass-fleece-jacket-1621171.html%3F

It would be *so much better* if uMatrix plucked out that target URL and let me click on through.

**Comment by elypter** [comment]
there is an extension called cleanlinks that does this

**Comment by foresto** [comment]
I'm using cleanlinks. It doesn't solve this problem.

**Comment by gorhill** [comment]
https://github.com/gorhill/uMatrix/wiki/How-to-get-past-%22uMatrix-has-prevented-the-following-page-from-loading%22#bypass-redirects
