### ISSUE TITLE
Youtube fullscreen disabled

### ISSUE THREAD

**Issue by BItim** [gorhill/uMatrix#503]
When using uMatrix on Firefox, the fullscreen option of Youtube is disabled, even when I approved all Youtube resources.
Screenshot:
![youtube](https://cloud.githubusercontent.com/assets/4103710/13352019/37c1a208-dc93-11e5-87c1-8ece1989b004.png)

**Comment by gorhill** [comment]
Unable to reproduce. You will have to make a better case that this is a uMatrix issue -- and a requirement for making a case is to provide way more details -- and that include _provide a URL_. See [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).

**Comment by mbme** [comment]
this issue might happen because of user agent spoofing

**Comment by BItim** [comment]
@mbme you where right. Problem solved by disabling user agent spoofing. 
Thanks.

**Comment by gorhill** [comment]
> url is irrelvent because it happens in all videos.

It's not irrelevant:

- it prevents me to go on a quest to find a video -- providing a URL which I can just click is being considerate;
- it makes **100%** sure that whatever the issue is, it's not with the specific video -- I don't care that _you_ can reproduce it with any video, I want the specific video with which you did reproduce it.
