### ISSUE TITLE
0.9.3.2 Show the number of distinct requests on the icon; Never resets/zeros on page reload.

### ISSUE THREAD

**Issue by nSpecter** [gorhill/uMatrix#504]
Firefox 44.0.2

Request to have the "requests number" displayed on the uMatrix toolbar icon reset to zero when the page is reloaded. 

As it is now, the number just increases ever skyward until it hits ">1k" whenever the page is reloaded, either by pressing "Reload the page" in uMatrix, pressing F5 in the browser or even hitting the browser's Back button.

I find this number particularly valuable to watch when trying to determine the minimum number of elements to unblock on particularly recalcitrant websites with a bazillion ad affiliates and trackers. ;)

Thanks and great job on a fantastic tool.

**Comment by gorhill** [comment]
It's by design, page reload do not cause the matrix to reset. For a given web page in a given tab, the matrix is reset a few minutes after the page has been unloaded. This is to be sure that *all* the places where a page caused the browser to connect are reported in the matrix, we wouldn't want information about rare instances of connection to be flushed away on a mere page reload.

**Comment by nSpecter** [comment]
Got it. Thanks.
