### ISSUE TITLE
Feature Request: Domain Lookup

### ISSUE THREAD

**Issue by eromlige** [gorhill/uMatrix#505]
If I see a domain in the list accessed by a site, sometimes I like to know what/who those domains represent, so I can sort of gauge my willingness to put myself at risk. It would be cool if I could right click on a domain, get a context menu and use a site like Alexa, Quttera, VirusTotal, NoScript, Google Safe Browsing Diagnostic, to get a bit more info.

`ex. [RightClickDomain]--> |Context Menu| --> {Send To.. || Check Domain || More Info} --> [NoScript] `

And get sent to: https://noscript.net/about/outbrain.com;outbrain.com with said domain.

Dunno, just thought it would be cool.

**Comment by nazir-cz** [comment]
I recently switched from noscript to umatrix  and I also lack this feature...

**Comment by Snapy** [comment]
There are two aspects about the feature implementation in NoScript : 
* setting up a personal domain & 
* redirecting to 3rd-party servers to check for privacy/security.
The first one has already been discussed many times by @gorhill : he doesn't want having to maintain a website (was about uBO and was a couple months ago) because it requires time which he doesn't have as he prefers to focus on coding ; it also costs money for the server/bandwidth and he doesn't want donations as it may involve expectations from donators and may make them feel as if gorhill is for hire possibly asking for _specific_ (ie for a handful of users) feature requests.
The second aspect would rely on 3rd-party servers (see #185).
@nazir-cz You can and should keep NS as it offers additional protections (clickjacking, XSS, ABE to name a few) even when you allow all scripts.
@eromlige You can use FlagFox although it checks only the age domain you can set up more custom tools with keyboard shortcuts.

**Comment by gorhill** [comment]
Duplicate of #65.

**Comment by eromlige** [comment]
@Snapy @gorhill 
Fair enough, thank you for the response. I still love uMatrix, and keep up the good work!
