### ISSUE TITLE
No number in icon

### ISSUE THREAD

**Issue by mikhaelkh** [gorhill/uMatrix#513]
Chrome 49.0.2623.75 beta x64
Windows 7 SP1 x64
https://alternativeto.net/software/7-zip/
When open and reload(Ctrl+F5) link sometimes there's no number on icon

**Comment by offhub** [comment]
Page load: OK
1st refresh: OK
2nd and later: No number on icon

**Comment by puff-m-d** [comment]
Hello gorhill,
I do not like to make many suggestions but...
I realize that the is only a very minor issue (more cosmetic than anything else), but I have several systems that I cannot use beta extensions on (can only use those from Chrome Store). It has been several months since this fix was implemented but it has never been published to the Chrome Store yet.
Do you plan on publishing it anytime soon (maybe it has just been overlooked)?
Thanks for all the work you put into both uMatrix and uBlock.
Best regards,
Kent

**Comment by gorhill** [comment]
Sorry, didn't realize I had not updated the Chrome store version. I just published it, don't know how long it will take to become available.

**Comment by puff-m-d** [comment]
No problem at all...
It is already showing in the Chrome Store...
Thanks for all you do!
Best regards,
Kent
