### ISSUE TITLE
Please allow all PINK URLs and Columns with a single, say reload click?

### ISSUE THREAD

**Issue by kawiv2k** [gorhill/uMatrix#520]
Sorry it's not a bug, Request For Enhancement. Please put a check box in the settings to option temporarily allowing all of the "Pink" rated sites and screened actions each time a page reload is done, but only if nothing else was manually clicked (differentiating whether wants wants to use the feature on this particular page or pick and choose manually). Most pages won't even work properly if I don't click all the pink boxes with counts and reload. You're allowing us to whitelist all, please allow us to whitelist "semi-safe". I typically just follow the tool's recommendation anyway, not allowing any RED sites so this feature would allow me to do with a click what I otherwise do manually repeated times. Tons of pages will load nested scripts that get called from the ones I've just enabled so it can be a tedious process to make a page work. so, if even one box is clicked before a reload then it would be manual operation like it is now, otherwise one could keep clicking reload until all of the less threatening scripts have loaded. Each reload would reset the prior manual mode until another box was clicked. 

It's a great invention BTW. I really appreciate having it.

Thanks!
Michael

**Comment by gorhill** [comment]
Click the `all` cell?

**Comment by kawiv2k** [comment]
Oh, I see. Very good. I thought the all cell was the same as whitelisting everything. I suppose I need to dig into the documentation a little more. I also want to automatically deny social media when I'm surfing, which I think I saw was possible using the rules editor, but I haven't looked at the details yet for allowing on the rare time I actually look at a facebook page vs just all of the sites that think they need to link it.
OK then, this case is closed, nothing to see here, move along.....

**Comment by gorhill** [comment]
If you want to work in allow-all/block-exceptionally mode (i.e. toggling the `all` cell to _allow_), then blocking ubiquitous 3rd parties as you spot them is just a matter of selecting the global scope (the asterisk `*` in the scope-selector menu), and blocking the whole domain of those 3rd parties:

![a](https://cloud.githubusercontent.com/assets/585534/13724637/372712e2-e85a-11e5-8aa6-3391915cf899.png)

Pic above shows the blocking of `facebook.com`, `facebook.net`, `twimg.com`, twitter.com` everywhere by default (because these rules were created while the global scope is selected).

Then click the padlock to commit these rules, and be sure to revert back to local scope to avoid mistakenly setting rules in the global scope next time you open the popup panel.

**Comment by gorhill** [comment]
Then if you land on a `facebook.com` page, which will be wholly blocked as a result of above rules, it's a matter of creating a local _allow_ rule for `facebook.com`, `facebook.net`:

![a](https://cloud.githubusercontent.com/assets/585534/13724781/d9945708-e85d-11e5-8639-a92b75dafba6.png)

![c](https://cloud.githubusercontent.com/assets/585534/13724782/dc69c648-e85d-11e5-9f6f-e10f2cc4c39d.png)

**Comment by kawiv2k** [comment]
Nice, thanks!
