### ISSUE TITLE
Add Decentraleyes-like functionality to uMatrix ?

### ISSUE THREAD

**Issue by BeTmAsTeR** [gorhill/uMatrix#547]
I'm talking about this firefox extension:
https://addons.mozilla.org/it/firefox/addon/decentraleyes/

Often some JS lib are needed to make a website work properly, by using an offline version of those libs uMatrix can make the page loading faster and block the tracing capabilities of some well-known CDN.

**Comment by CrisBRM** [comment]
uBlock used to have a similar functionality, except I believe it cached CDNs on the fly. It was called 'local mirroring' and was ultimately disabled because it broke some sites. Never had a problem with it, personally.

Gorhill said he had plans to make a separate extension with the functionality, but he's either dropped them or hasn't gotten around to it yet.

**Comment by BeTmAsTeR** [comment]
what are the plans ? @gorhill

**Comment by gorhill** [comment]
Plan is to decline.
