### ISSUE TITLE
NoScript + uMatrix = cookie leak

### ISSUE THREAD

**Issue by scratchyleet** [gorhill/uMatrix#554]
**Requirements:**
- Firefox 46.0.1.
- uMatrix 0.9.3.3.
- NoScript 2.9.0.11.

**Reproducing steps:**
- Create a new profile.
- Install uMatrix.
- Install NoScript.
- Close a browser.
- Open a browser.
- Close a browser.
- Open a browser.
- Open page https://github.com/gorhill/httpswitchboard/wiki
- Find string "Are cookies blocked?". Open its link in a new tab.
- Press uMatrix icon. Press lower half block under "cookie" opposite to the right from "raymondhill.net". (or just block cookies to raymondhill.net) Press "lock" icon. ("Save all temporary changes for this scope.")
- Close a browser.
- Open a browser.
- Open page https://github.com/gorhill/httpswitchboard/wiki
- Find string "Are cookies blocked?". Open its link in a new tab.
- Press "Reload current page" icon.

Marvelously works at first browser start. If you close a tab and open it again it won't happen. Unless you restart a browser.

**Temporary** _(known)_ **workaround:**
- Disable NoScript. Completely.
- Close a browser.
- Open a browser.
- Close a browser.
- Open a browser.
- Open page https://github.com/gorhill/httpswitchboard/wiki
- Find string "Are cookies blocked?" and open its link in a new tab.
- Press "Reload current page" icon to check if it worked.

Good luck fixing that.

**Comment by gorhill** [comment]
Everything works fine here.

**Comment by gorhill** [comment]
I could reproduce, somehow, need to figure out how.

**Comment by gorhill** [comment]
Finding so far:

With NoScript enabled, the data uBO attaches to the channel instance in its http observer can no longer be found. This could be because this data is trashed somehow, or because NoScript creates an entirely new channel instance, causing the older one to b discarded. Will need insights from NoScript people.

**Comment by gorhill** [comment]
By the way, "cookie leak" is just _one_ symptom of the issue here, the bigger problem is that other parts of uMatrix are crippled by the loss of contextual data when NoScript is enabled.

**Comment by gorhill** [comment]
@laniakea64 Any quick insight about why the channel data is lost (or why the channel at `http-on-modify-request` time is not the same as the one at `http-on-opening-request`)?

**Comment by laniakea64** [comment]
Now that you mention it I seem to recall something about NoScript cloning channels but can't remember exactly what (or when).  Any suggestions what to search for in the NoScript code?

**Comment by gorhill** [comment]
I am currently looking [here](https://github.com/avian2/noscript/blob/7bdcefb0072016debff679c597d77833df1dd069/xpi/chrome/content/noscript/Policy.js#L45), it seems this is called for every `http-on-opening-request`.

**Comment by gorhill** [comment]
If I un-check NoScript's _"Enable ABE"_, the issue goes away.

**Comment by laniakea64** [comment]
Unfortunately for debugging, that "Enable ABE" checkbox in practice disables more than just ABE itself...

I'll play around with this some and post back if I find anything useful.

**Comment by gorhill** [comment]
[ABE.js](https://github.com/avian2/noscript/blob/master/xpi/chrome/content/noscript/ABE.js) uses `ChannelReplacement` objects, defined [here](https://github.com/avian2/noscript/blob/master/xpi/chrome/content/noscript/ChannelReplacement.js).

**Comment by laniakea64** [comment]
I don't seem to be able to reproduce the issue either with SeaMonkey or with Firefox 46.0.1.  Can please clarify the instructions "Close a browser" and "Open a browser" - does "browser" refer to a browser tab, browser window, the whole application, or..?  Also, is there something special about the cookie testing page on raymondhill.net and/or accessing from Github that makes this impossible to reproduce on a local server?

(In case it could be platform-specific, I'm running Linux x86_64)

**Comment by gorhill** [comment]
The repro steps for me are these:

- Enable uMartix and NoScript.
- Go to <http://raymondhill.net/httpsb/httpsb-test-cookie-1.php>.
- Configure uMatrix so that cookies are blocked for `raymondhill.net`, persist.
- Close the tab.
- Quit Firefox.
- Launch Firefox.
- Go to <http://raymondhill.net/httpsb/httpsb-test-cookie-1.php>.
- Force a reload of the page: uMatrix is *not* supposed to say that the server received a cookie.

**Comment by laniakea64** [comment]
Thanks gorhill, I can reproduce the issue in SeaMonkey with that set of steps-to-reproduce (on the last step, forcing reload from uMatrix).

Apparently this is not due to a recent change in NoScript - I'm getting the same result with every NoScript version that actually works with a modern browser.  I'll try debugging NoScript a bit, see if I can find where exactly the data is getting lost...

**Comment by laniakea64** [comment]
Been trying to see if it's possible to resolve this with a patch to NoScript, haven't cracked this one so far although I did find out that if I cause an error in the initialization code for `ABERequest` objects then the issue goes away (but probably at the expense of borking NoScript, despite the total lack of any error messages)

I'll see if we can bring Giorgio in this if I don't solve it soon.

**Comment by gorhill** [comment]
How do you debug NoScript? It does not show up in the list at `about:debugging#addons` on my side.

**Comment by laniakea64** [comment]
Oh, I'm not doing that kind of debugging, I just modify the xpi and insert `dump()` calls in possibly-relevant places in the code and hope something means anything? :confused: 
Was trying to see if there's a point in the NoScript code where the channel still has its `umatrixreqdata` and where it doesn't, and go from there.  Now I'm trying to work backwards from the fact that disabling ABE gets it working.

**Comment by laniakea64** [comment]
OK here is what I think is going on.  NoScript uses `redirectTo()` method of HTTP channels and it is `redirectTo()` itself which is causing uMatrix data to be dropped.  If I comment out this line in NoScript's ChannelReplacement.js (making no other changes) then uMatrix works as expected:
```
      chan.redirectTo(this.newURI);
```

I'm thinking it's not a NoScript bug per se but maybe Giorgio can at least work around it.

**Comment by laniakea64** [comment]
informaction: https://forums.informaction.com/viewtopic.php?f=10&t=21926

**Comment by hackademix** [comment]
Giorgio here.
What kind of properties does uMatrix set on the channel?
Depending on whether they're expected to be persisted across "normal" redirections (as it happens for nsIPropertyBag ones) we could either file (and possibly fix) a Mozilla Necko bug to make redirectTo() mimic more closely HTTP redirections, or uMatrix could use a ChannelEventSink to set them on the new, redirected channel.

**Comment by gorhill** [comment]
> uMatrix could use a ChannelEventSink to set them on the new, redirected channel.

That's what uMatrix does already ([see here](https://github.com/gorhill/uMatrix/blob/5fe51be81417a41c4f0f7e741a160b720413540c/platform/firefox/vapi-background.js#L2052)).

The properties are the tab id (string), request type (number) ([see here](https://github.com/gorhill/uMatrix/blob/5fe51be81417a41c4f0f7e741a160b720413540c/platform/firefox/vapi-background.js#L2048) -- the comment is not accurate, the attached data is also useful for other phases of the request: `http-on-modify-request`, `http-on-examine-response`).

**Comment by gorhill** [comment]
I don't have time to investigate more for now, but I just found that [this line](https://github.com/gorhill/uMatrix/blob/5fe51be81417a41c4f0f7e741a160b720413540c/platform/firefox/vapi-background.js#L2067) seems to throw an exception. So that could be the problem?

**Comment by gorhill** [comment]
Correction to my comment above: there is no exception, it seems to just be a debugger quirk, giving the impression that an exception is throw.

Something else I found: uMatrix properties are not attached on the channel in the first place because `http-on-opening-request` is never fired if the debugger is to be believed. I see only `http-on-modify-request` and `http-on-examine-...` notifications.

So at this point it comes down to find out why `http-on-opening-request` is not fired for uMatrix in the current scenario.

**Comment by gorhill** [comment]
Latest finding is that `http-on-opening-request` is not fired for uMatrix in the reported problematic scenario. When I force a refresh of the page, this is what uMatrix is notified about:

    uMatrix: 69 observe() url="http://raymondhill.net/httpsb/httpsb-test-cookie-1.php" topic="http-on-modify-request")
    uMatrix: 70 asyncOnChannelRedirect() url="http :// raymondhill.net/httpsb/httpsb-test-cookie-1.php"
    uMatrix: 71 observe() url="http :// raymondhill.net/httpsb/httpsb-test-cookie-1.php" topic="http-on-modify-request")
    uMatrix: 72 observe() url="http :// raymondhill.net/httpsb/httpsb-test-cookie-1.php" topic="http-on-examine-response")

The number following "uMatrix" is a simple counter to be sure to understand the sequence of event in time.

If I disable NoScript, `http-on-opening-request` is fired every time I force a refresh

    uMatrix: 84 observe() url="http :// raymondhill.net/httpsb/httpsb-test-cookie-1.php" topic="http-on-opening-request")
    uMatrix: 85 observe() url="http :// raymondhill.net/httpsb/httpsb-test-cookie-1.php" topic="http-on-modify-request")
    uMatrix: 86 observe() url="http :// raymondhill.net/httpsb/httpsb-test-cookie-1.php" topic="http-on-examine-response")

**Comment by hackademix** [comment]
That's expected, because NoScript uses this internal redirection to delay anti-CSRF protection processing until DNS resolution is complete to mitigate DNS rebinding attacks.
As I suggested earlier, the problem appears to be caused by

1.  `redirectTo()` not copying the extra properties from the old channel to the new one (opposite to what happens for "organic" redirections) and
2. `http-on-opening-request` never being called for any redirection (by design).

An easy work-around would be assigning your extra properties in `http-on-modify-request`, I guess.

**Comment by gorhill** [comment]
> An easy work-around would be assigning your extra properties in `http-on-modify-request`, I guess.

This also mean that any extension which relies on `http-on-modify-request` would have to implement such workaround just for the sake of working properly with NoScript specifically.

I could probably add a code path to uBO/uMatrix for the sake of working around `http-on-modify-request`, but that does not feel right to have such a workaround just in case one other specific extension is installed.

**Comment by hackademix** [comment]
> This also mean that any extension which relies on http-on-modify-request would have to implement such workaround just for the sake of working properly with NoScript specifically.

Not quite. It just means that you should not modify requests (e.g. by adding headers or properties) in "http-on-opening-request": as the name suggests, the proper place is "http-on-**modify**-request".

Furthermore, this bug is not triggered _specifically_ by NoScript, but by any add-on (or Gecko internal code) which uses `nsIHttpChannel.redirectTo()` (and this is gonna be quite common in the brave new WebExtensions world, since webRequest's `redirectUrl` implementation does exactly that).

**Comment by gorhill** [comment]
> you should not modify requests (e.g. by adding headers or properties) in "http-on-opening-request"

Neither uBlock or uMatrix do this. Headers are modified strictly at `http-on-modify-request` and/or `http-on-examine-response` time.

> this is gonna be quite common in the brave new WebExtensions world, since webRequest's redirectUrl implementation does exactly that

With Chrome API, never does the use of redirection prevent `onBeforeRequest` from being properly fired to all listening extensions.

I strongly believe that it is reasonable for an extension subscribing to `http-on-opening-request` to always be notified through `http-on-opening-request` for every new request. This is the issue here, the `http-on-opening-request` event is being "eaten" from the point of view of those extensions which listen to `http-on-opening-request` events.

**Comment by hackademix** [comment]
>> You should not modify requests (e.g. by adding headers or properties) in "http-on-opening-request"

> Neither uBlock or uMatrix do this. Headers are modified strictly at http-on-modify-request and/or http-on-examine-response time.

Maybe I misunderstood the whole issue, then: do or do not your add-ons modify the request by adding custom properties in "http-on-**opening**-request"? If they actually do, please move that modification code in "http-on-**modify**-request".

> With Chrome API, never does the use of redirection prevent onBeforeRequest from being properly fired to all listening extensions.

In facts, Firefox's `onBeforeRequest` implementation relies on "http-on-modify-request", not on "http-on-opening-request": therefore WebExtensions themselves will work just fine, but legacy add-ons which use http-on-opening-request will get confused by WebExtensions' redirections.

> I strongly believe that it is reasonable for an extension subscribing to http-on-opening-request to always be notified through http-on-opening-request for every new request.

No, i think it's not. The [docs](https://developer.mozilla.org/en-US/docs/Observer_Notifications) do not guarantee this, and discourage its usage unless you've got a very narrow use case for it:

> **http-on-opening-request** - Similar to http-on-modify-request, but called earlier (synchronously during the channel's asyncOpen() call), and some channel atttributes (proxyInfo) may be missing. **Use only if** your observer must be called before asyncOpen returns.

At any rate, http-on-opening-request observers are not notified for redirections, [there's specific Necko code in nsHttpChannel.cpp guaranteeing this](https://dxr.mozilla.org/mozilla-central/source/netwerk/protocol/http/nsHttpChannel.cpp#5271), so if you need to process redirected channels just do not rely on that notification.

**Comment by gorhill** [comment]
> In facts, Firefox's onBeforeRequest implementation relies on "http-on-modify-request", not on "http-on-opening-request"

Thanks for the information. I really want to be sure I understand properly all this. The doc on `chrome.onBeforeRequest` says this (my emphasis):

> onBeforeRequest (optionally synchronous)
> Fires when a request is about to occur. **This event is sent before any TCP connection is made** and can be used to cancel or redirect requests.

Is this also true for Firefox's `http-on-modify-request`?

**Comment by hackademix** [comment]
> Is "sent before any TCP connection is made" also true for Firefox's http-on-modify-request?

Yes, unless of course it's a previously established persistent connection (same host, Connection: Keep-Alive), which I'm pretty sure happens also for Chrome's onBeforeRequest, despite the ambiguous promise made by the doc (but I believe it's not relevant for our own use cases, is it?)

**Comment by gorhill** [comment]
> Yes

Well then, I should be able to move everything at `http-on-modify-request` with little modifications for both uMatrix/uBO.

**Comment by davidhedlund** [comment]
@gorhill > uBlock Origin ("uBO") and uMatrix must be considered incompatible with NoScript.

ABP can be used with NoScript without any problems.
