### ISSUE TITLE
can we have an option to disable vertical inheritance?

### ISSUE THREAD

**Issue by requiredregistration** [gorhill/uMatrix#584]
for example, at https://gitlab.com/u/gitlab, because of the inheritance feature, allowing script on gitlab.com will not block the request to piwik.gitlab.com by default, and data will be collected.

**Comment by gorhill** [comment]
Just block `piwik.gitlab.com`. I really do not intend to change the UI, it is set in stone. One could add knobs and switches until the add-on become incomprehensible, I want to keep it simple just as it is now.

**Comment by requiredregistration** [comment]
then it will be too late. the collection of the data will have taken place. nothing will change the GUI, it will be a dashboard.html#settings option for advanced users.

**Comment by requiredregistration** [comment]
piwik.gitlab.com appears ONLY after the script from gitlab.com has ran.

**Comment by gorhill** [comment]
You already trusted gitlab.com, piwik.gitlab.com is 1st-party to gitlab.com. You are creating an issue out of thin air, and asking a major change in how UI matrix works to address this made up issue. Data collection could very well take place also on gitlab.com, and yet you trusted it.

**Comment by requiredregistration** [comment]
you misunderstood.

the issue is not about trust, and i am aware of what data can be collected through common web browser usage with and without umatrix.

the issue is that it is not possible to allow ONLY `gitlab.com` because of the inheritance functionality.
the capability to disable inheritance would have blocked `piwik.gitlab.com` by default, and because it is not currently possible to disable it, it is allowed by default. further actions can only be taken after it was allowed at least once for a user who is not aware that a request to `piwik.gitlab.com` will be sent by reloading after allowing script on `gitlab.com`.

it is about making umatrix even more strict. inheritance in these cases can decrease security and can cause more privacy problems.

**Comment by gorhill** [comment]
> it is about making umatrix even more strict. inheritance in these cases can decrease security and can cause more privacy problems.

Just use uBO's dynamic URL filtering, because by your logic, allowing all scripts from `gitlab.com` "decrease security and can cause more privacy problems". The logical consequence of the logic of your argument is that you should allow scripts on a per-script basis -- and that is not uMatrix. It can be done with uBO though it's not an optimal UI for that purpose.

**Comment by anewuser** [comment]
Duplicate: #435.

**Comment by requiredregistration** [comment]
you are still misunderstanding the issue or you are being dishonest now.

i do not want to block specific scripts. i want an option to disable the vertical inheritance functionality.

it is not a duplicate. that is why i never said anything about scopes. i am talking about a global option for advanced users, and what i asked for does not require any UI changes.

**Comment by anewuser** [comment]
![c2e682de-9fc9-11e4-9f08-503c0526ebbc](https://cloud.githubusercontent.com/assets/6733770/16705689/9f415896-4567-11e6-83b3-5e8541b263ba.png)

**Comment by requiredregistration** [comment]
it is about the user having complete matrix control. the inheritance takes away some of that control from the user.

**Comment by anewuser** [comment]
Not "the user", but **you**. Use something more specific than uMatrix.

**Comment by adrienbeau** [comment]
So, with the option you propose, if a domain was allowed, in the matrix, only the top-level domain would be green, all its subdomains would appear red until you clicked them. Also, if you had a list of a domain and subdomains all green, clicking on the domain would turn it red, but all subdomains would remain green.

This would mean that when uMatrix encounters a subdomain for which there is no configuration, it would not look up the domain hierarchy, but simply block it. This would also mean you have to create a lot more rules, because each subdomain you want to enable now has to be explicitly listed. I agree this can be seen as "more secure".

Interesting idea.

**Comment by gorhill** [comment]
> or you are being dishonest now

GPL, fork, etc.
