### ISSUE TITLE
toolbar icon gone in private browsing window

### ISSUE THREAD

**Issue by laniakea64** [gorhill/uMatrix#586]
**Environment:**
SeaMonkey 2.40
uMatrix self-build from https://github.com/gorhill/uMatrix/commit/2ef2505507b9af2242e2fd09e32921ff9ec4a669
new profile

**STR:**
1) install uMatrix, restart browser
2) verify that the toolbar icon is visible, which it is by default
3) File > New > Private Window

**Expected results:** the uMatrix toolbar icon is visible in both windows

**Actual results:**
The uMatrix toolbar icon is in the normal window but not present in the private window, not even available under toolbar customize.
Nothing related in Error Console.

**Comment by gorhill** [comment]
The problem is that the test `wintype !== 'navigator:browser'` at [line 1248](https://github.com/gorhill/uMatrix/blob/941d7102475cec8bc7b39d32d28c79cfa067d951/platform/firefox/vapi-background.js#L1248) always succeed. uMatrix give up trying after 8 tries.

uBO is not affected by the issue, but this is a part I revised in uBO. I do notice a delay before the icon appears in uBO, so probably if uMatrix tried more, it would eventually be able to add its icon to the toolbar.

The code to add the icon in uBO is time-based -- it will give up after a set time, while the code to add the icon in uMatrix is try-based, it currently gives up after 8 tries. Solution will be to bring uBO code to uMatrix regarding toolbar icon handling.

**Comment by gorhill** [comment]
I could fix the icon issue, but looking closer, there are other more serious issues with both uBO and uMatrix: the content of the popup panel in a private window does not match the web site of the current selected tab. Actually, it appears the popup panel depends on the tab selected on the original, non-private one.

**Comment by gorhill** [comment]
I confirm that the cause for the other issue described above is also because the `windowtype` attribute is not set for the private window. Wherever I look, the FF documentation is clear regarding `windowtype`:

> Browser windows have a window type of `navigator:browser`.

This is not happening for a private window in SeaMonkey. I wonder if this is a bug in SeaMonkey.

**Comment by laniakea64** [comment]
Yep, looks like a SeaMonkey bug - the `windowtype` of private window is an empty string.

**Comment by gorhill** [comment]
I have a fix which is to further see if the `id` attribute is `main-window` as a fallback in case the `windowtype` is not `navigator:browser`. Seems to work fine, but the fix is entirely dependent on my observations using the debugger -- not of any documentation.

**Comment by laniakea64** [comment]
We've talked to the SeaMonkey devs, and got confirmation that A) this is indeed a SeaMonkey bug (likely affecting much more than just uBlock Origin & uMatrix), and B) your chosen work-around should be stable until it's fixed.

Apparently SeaMonkey is using removal of the `windowtype` attribute as its way of flagging private windows as private windows :confused:

someone will be filing on Bugzilla about this soon, I will update this comment with the link
