### ISSUE TITLE
uMatrix incompatibility with Remember The Milk web app

### ISSUE THREAD

**Issue by IpsmLorem** [gorhill/uMatrix#608]
I found some incompatibility with the "Remember the milk" Web app (https://www.rememberthemilk.com).

When scrolling in the task list, the firefox console display :

`CustomError: Error in protected function: Operation is not supported`

And when hitting the end key on the keyboard :

`CustomError: Error in protected function: a.setBaseAndExtent is not a function`

And fire each scroll step a xHR :

`https://www.rememberthemilk.com/app/errors?script=https%3A%2F%2Fwww.rememberthemilk.com%2Fapp%2F_%2F1963%2Fcompiled.1963.fr.js&error=Operation%20is%20not%20supported&line=25884`

I tried with 

`matrix-off: rememberthemilk.com true`

with no luck.

I tried completely disable uMatrix addon and it worked.

I encountered the same incompatibility (sometimes) with text input in Facebook too but did less experiment with it.

**Comment by gorhill** [comment]
Did you try disabling all the per-site switch as well?

**Comment by gorhill** [comment]
Anyways, not enough investigation went into this issue as per report in order to make the case there is an issue with uMatrix. No word of logger output. No word of per-site switches. No word on browser and version. etc.Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
