### ISSUE TITLE
Chrome Incognito.

### ISSUE THREAD

**Issue by Penguin-Guru** [gorhill/uMatrix#620]
Sorry for posting multiple issues in quick succession but there is no rush to respond to them.

I have noted that, when uMatrix is allowed incognito, saved listing behaviour is visible from the extension menu when not incognito. I understand the information needs to be saved and made accessible somewhere for management but I believe this behaviour is unintuitive and potentially dangerous for careless users. I assume the Fire Fox extension behaves in a similar manner.

Ideally, I think incognito configuration data could be encrypted and decrypted only for the incognito session, but I have no idea how this could be done. One quick solution is to simply warn users of this behaviour when they attempt to allow uMatrix incognito. Perhaps a compromise would be to conceal incognito data in the uMatrix menu when not incognito, but not actually encrypt the data.

**Comment by WillemMali** [comment]
I don't think this feature would make a lot of sense as by design Chrome extensions share data between incognito and regular mode, but if you're on Linux and can do some scripting you can implement it yourself. The way to go about it would be:

1. Create a separate Chrome profile for incognito browsing (you can do this by calling Chrome with a specific profile directory set, this is a command line parameter)
2. Install uMatrix there
3. Create a shortcut to Chrome with the special profile as a parameter, and the "start in incognito" parameter set

This would implement a separation between incognito blocklists and non-incognito blocklists. To get encrypted lists, I think it would be easiest to then:

4. Encrypt your incognito folder
5. Write a script that prompts for your encryption password, mounts/extracts the folder (in case of exctracting: don't forget to remove it once Chrome terminates!), and run Chrome with the parameters as described in 3

The same would go for Chromium, and I think Firefox also has profile/settings folder support.

**Comment by dragon788** [comment]
I would agree that this isn't within the scope of the extension. You are requesting functionality that Chrome itself doesn't implement, the only thing incognito really does is enable automatic deletion of cookies and disables (some) of the autocomplete and URL history. What you are looking for is a completely separate profile per Willem's suggestion with everything disabled or better yet a self destructing profile or something like the Tor browser.

**Comment by Penguin-Guru** [comment]
Alright, thank you. I think it would be nice if this functionality could be made more accessible for others but it is (barely) accessible enough for me. Very interesting method! I will try scripting it in the future.

If it is possible to detect incognito state, the incognito rules could at least be grouped into a separate tab or collapsed menu in the interest of privacy and to allow for easily clearing only those rules. Then those rules could be handled differently, ideally they would not be applied for normal browsing and then they would be deleted automatically when the incognito session ends. Normal rules could be copied into the incognito rule list when the session begins so that modifications incognito are not applied to the normal rules. This behaviour is probably more intuitive for incognito, if it is even possible, but I understand that it might not be worth the work. Just an idea. The simple warning would really be enough of a precaution.

I think it is (or was) possible: http://stackoverflow.com/questions/11928788/how-to-detect-incognito-mode-from-extension-background
