### ISSUE TITLE
UA spoof in uMatrix doesn't work on iFrames.

### ISSUE THREAD

**Issue by crssi** [gorhill/uMatrix#649]
UA spoof in uMatrix doesn't work on iFrames.

Enable UA spoof and go to https://www.browserleaks.com/javascript
Pay attention on "User-Agent" info.
On top, you have two buttons "window" and "iframe.contentWindow"... click on both... the real UA is revealed under "iframe.contentWindow".

At this time I would also like to thank you for deliver us your great addons.

Cheers

**Comment by Roman-Nopantski** [comment]
FWIW, I do not believe this is a uMatrix issue. I use (in Firefox) UAControl to spoof headers and User-Agent JS-Fixer so JS matches. I get the same result as you.

window says FF 45, iframe says FF 49 .. maybe someone can dig a little deeper. crssi, what browser are you using?

**Comment by crssi** [comment]
Firefox 45 ESR and FF 49. Tested with uMatrix for UA spoof and with and without UA JS Fixer.
I normally dont use UA spoof anymore, since I have a feeling that this is futile, but every once and then I test all kind of stuff. ;)

**Comment by Roman-Nopantski** [comment]
@crssi I just spoof to the latest FF ESR. It's pointless trying to hide your browser model. Now I'm thinking its pointless trying to hide the browser version.

https://www.torproject.org/projects/torbrowser/design/index.html.en#fingerprinting-linkability
^ scroll down to "Strategies for Defense: Randomization versus Uniformity"

**Comment by acrobat1** [comment]
So this is basically hopeless for the time being, meaning that as we speak neither uMatrix , or some specific user-agent extension (or maybe a combination of both) can successfully spoof the real user agent in some circumstances ? Not even limiting it to just the browser version ?

As a side note, does this kind of detection on iFrames still need javascript enabled to work, or is it always effective regardless?

**Comment by Roman-Nopantski** [comment]
@acrobat1 yes, JS needs to run to return the UA string. Obviously, these are worst case scenarios - the best defense is to block as much (or all) unnecessary JS (and other leaks such as css, etc), which is what uMatrix and uBlock Origin are all about.

https://github.com/pyllyukko/user.js/issues/193#issuecomment-259157324

If the UA string was that important a metric in fingerprinting (and it can be fairly high entropy), then it wouldn't be hard to use 1st party scripts that are based on feature detect. Just my 2 cents on it :)

**Comment by forkoz** [comment]
Heh, beat me to the punch. I'm unfortunately stuck with chrome on linux. uMatrix UA spoofing gives away my platform even in the current window. It makes you stand out a bit more to have windows or mac running on linux. 

There was only one extension in the chrome store that changed this value and its only correct for mac (macintel is right, "windows" is not) I can confirm the iframe behavior with the extension I'm using as well. As an added bonus, the appversion gives away the real string too, at least on chrome. 

In windows I have RAS and it mimics things surprisingly well. The iframe bug is not present there either.
My point in spoofing the browser/platform is so that exploit code targets the wrong setup and its proved by places with super invasive ads trying to serve me .DMGs because my mac runs "slow".
