### ISSUE TITLE
Website popups will not load if they require external sources

### ISSUE THREAD

**Issue by Dbz** [gorhill/uMatrix#668]
### Describe the issue

If a website needs to make a popup (support chat in a pop up for example), then ublock doesn't add sources (more rows) in the extension table (the thing that pops up when you click the extension) for the popup. The popup just won't load. The only solution is to copy the url of the popup and load it in a new tab.

### One or more specific URLs where the issue occurs

Click on "Chat with us" which will make a popup: https://fiber.google.com/support/#tab=plans
It will create a popup to a link such as: https://secure.livechatinc.com/licence/7251891/open_chat.cgi?groups=1

However, the popup will not be able to load

### Steps for anyone to reproduce the issue

1. Go to https://fiber.google.com/support/#tab=plans
1. Click on "Chat with us"
1. If the popup is blocked by your web browse, white list it for this instance
1. The popup will not load

### Settings

- Browser/version: Chrome Version 54.0.2840.98 (64-bit)
- uMatrix version:  0.9.3.6

**Comment by adrienbeau** [comment]
**Unable to reproduce.**

Using Firefox 50.0, uMatrix 0.9.3.6, and my current ruleset (nothing fancy, except I use a very small list of blacklisted hosts), the popup loads on the first try. Here's the matrix for the fiber.google.com page:

![umatrix-668-1](https://cloud.githubusercontent.com/assets/13599352/20472917/7b36932e-afbd-11e6-8e4b-5315cbddc943.png)

And here's the matrix for the livechatinc.com page:

![umatrix-668-2](https://cloud.githubusercontent.com/assets/13599352/20472947/b0e3e864-afbd-11e6-8aec-128c0c9a6e82.png)

**Comment by Dbz** [comment]
It is possible that my browser being Chrome may make a difference, but I don't know.

I disabled matrix filtering for the scope at [Google Fiber](https://fiber.google.com/support/#tab=plans)

<img width="529" alt="screen shot 2016-11-20 at 10 50 52 pm" src="https://cloud.githubusercontent.com/assets/628429/20473271/5c466eba-af74-11e6-8fb6-f438c888fb19.png">

When the popup loads, even though I disabled matrix filtering for the scope, the popup's content doesn't load:

<img width="498" alt="screen shot 2016-11-20 at 10 52 10 pm" src="https://cloud.githubusercontent.com/assets/628429/20473295/7c3e328e-af74-11e6-84a9-ed8a6e46a987.png">

The additional sources that the popup needs to load from are not shown on the original page where it loaded from, so there is no way to enable them without loading the url in a different tab and then changing them there (Would a custom ruleset fix this?).

Here are the sources needed when the popup is loaded in a new tab:

<img width="530" alt="screen shot 2016-11-20 at 10 52 42 pm" src="https://cloud.githubusercontent.com/assets/628429/20473399/3cc8b0f6-af75-11e6-8cbc-b2ea04f19767.png">

**Comment by adrienbeau** [comment]
> It is possible that my browser being Chrome may make a difference

Of course, this is why users are asked to provide their uMatrix version and their browser version when they report issues.

> When the popup loads, even though I disabled matrix filtering for the scope, the popup's content doesn't load

The popup is an entirely different web page, on a different web domain, so the rules are entirely separate from the rules on the page that launches the popup. You disabled matrix filtering for the google.com scope (scope is shown in the top-left blue cell), this has no effect on the livechatinc.com scope. As can be seen in your second screenshot, matrix filtering is not disabled for that scope (and *it is blocking scripts from cdn.livechatinc.com* in that scope).

> The additional sources that the popup needs to load from are not shown on the original page where it loaded from

Of course, since they are different pages on different domains. The matrix only shows requests that were launched from the currently displayed page, for the currently displayed scope. Once the popup opens, the requests are managed from that popup, not from the original page.

> so there is no way to enable them without loading the url in a different tab and then changing them there

That is indeed a good way to troubleshoot popup issues. A popup is nothing but a normal web page, shown in a separate window.

> (Would a custom ruleset fix this?)

This is actually what you do when you click the "lock" icon. It persists your matrix settings, in effect it becomes a custom ruleset for the scope.

**Your issue, I believe, is the red "cdn.livechatinc.com" line in your second screenshot (for the livechatinc.com scope).** What you have requested is that all content from cdn.livechatinc.com is blocked, in your screenshot we can see one script has been blocked. Probably the script that displays the whole page/popup... Click on the line so that it becomes green, and reload the popup.

**Comment by gorhill** [comment]
Seriously... I say on the front page of the project:

> uMatrix does not guarantee that sites will work fine: it is for advanced users who can figure how to un-break sites, because essentially uMatrix is a firewall which works in relaxed block-all/allow-exceptionally mode out of the box: it is not unexpected that sites will break.

In the current case this is just a matter of adding `livechatinc.com cdn.livechatinc.com script allow`, or whatever rule will unblock js for `livechatinc.com`.

**Comment by gorhill** [comment]
> The additional sources that the popup needs to load from are not shown on the original page

By design: the popup is a different document from a different web site, merging rtwo different web sites into a single matrix does not make sense.

**Comment by gorhill** [comment]
> there is no way to enable them without loading the url in a different tab and then changing them there

Use he logger, the matrix panel is accessible there for any site, just click the second cell in a row entry.

**Comment by Dbz** [comment]
This is my first time contributing to this project, so I'm very unfamiliar with the terminology, so forgive me. I also have a custom ruleset, and I've been using uMatrix (and uBlock) for quite a while. Now that I have confirmed that this is expected behavior, may I suggest a feature? There are actually a couple ways I see to solve this, but what I prefer is in fact displaying two matrices on the host page.

![pagewithpopupcontext](https://cloud.githubusercontent.com/assets/628429/20496094/9e9f4e12-afd8-11e6-9a6c-682e5600d0f8.jpg)


This feature would allow all popups to be managed on the original page they came from without reloading the popup in a new tab. This isn't a problem for me on this one site, it happens every time there is a popup. Another alternative would be to allow matrix filtration on the actual popups because currently that's not an option:

<img width="498" alt="screen shot 2016-11-20 at 10 52 10 pm" src="https://cloud.githubusercontent.com/assets/628429/20496170/ea5c778a-afd8-11e6-9281-bc0cf7292a98.png">

This issue has been closed and marked invalid, but I see a flaw in the extension and a way to improve it. Is this a welcome change?

**Comment by Dbz** [comment]
@adrienbeau How do you feel about this proposed feature?

**Comment by Dbz** [comment]
@adrienbeau @gorhill  How do you feel about this proposed feature?

**Comment by gorhill** [comment]
Declined.
