### ISSUE TITLE
Which matrix rule syntax is correct -- wiki or browser extension?

### ISSUE THREAD

**Issue by chronokitsune3233** [gorhill/uMatrix#677]
**Edit: Feel free to close this. It was (mostly) a mistake to open this as an issue without reviewing commits first.**

The wiki syntax for matrix directives are described as follows:

    matrix: http://example.com on
    matrix: http://foo.org off

This differs from the Chrome extension's matrix directives, which are automatically changed to something like the following:

    matrix-off: http://example.com false
    matrix-off: http://foo.org true

This is a minor difference, but is there one that should be considered correct, or are both acceptable?

Edit: the source code seems to indicate another syntax is allowed:

    switch: http://example.com on
    switch: http://foo.org off

It seems the `matrix-off` syntax should be preferred. Is there a reason for the change?

**Comment by chronokitsune3233** [comment]
I see there were a lot of changes in [this commit](https://github.com/gorhill/uMatrix/commit/4aab150af363d36c46187a60040bd25e6aa23ac7), so `matrix-off` is the newer syntax. The reason for changing from `switch` to `matrix` apparently was that `switch` was too generic of a name and didn't really describe things.

I'm still not sure why `matrix: URI {on|off}` was changed to `matrix-off: URI {true|false}`, but it's something I can live with.

Sorry for any wasted time.

**Comment by gorhill** [comment]
I fixed the wiki documentation.

> I'm still not sure why `matrix: URI {on|off}` was changed to `matrix-off: URI {true|false}`, but it's something I can live with.

Originally there was only one switch, to control whether matrix filtering was enabled or not. This was changed because more type of switches were added, and in the process I decided that the _absence_ of a switch-based rule would be equivalent to its default state. Matrix filtering's default state is to be enable, hence the need for a `matrix-off` switch, to override the default state.

Also, it's cannot be a URI, it must be a hostname (or IP address).
