### ISSUE TITLE
Can we have a way of making global allows?

### ISSUE THREAD

**Issue by k-h** [gorhill/uMatrix#685]
Each website I go to that has embedded youtube videos, I have to allow youtube, google, yimg, google video etc.  And it all takes three or so reloads.  Boring, really boring.

Currently red and green are allow/disallow, how about say:

blue = global allow.

**Comment by jjohns71** [comment]
You can do this with uMatrix... To do this add the following rules to your 'My Rules' tab:

For YouTube:
  `* googlevideo.com * allow`
  `* youtube-nocookie.com frame allow`
  `* youtube-nocookie.com script allow`
  `* youtube-nocookie.com xhr allow`
  `* youtube.com frame allow`
  `* youtube.com image allow`
  `* youtube.com other allow`
  `* youtube.com plugin allow`
  `* youtube.com script allow`
  `* youtube.com xhr allow`
  `* ytimg.com image allow`
  `* ytimg.com plugin allow`
  `* ytimg.com script allow`


This can also be done through the GUI -- if you click on the domain at the top left of the uMatrix panel you can change it to * to implement a global rule. (Produces the same rules as given above.)

**Comment by k-h** [comment]
Thanks.

> if you click on the domain at the top left of the uMatrix panel you can change it to * to implement a global rule.

But that would allow everything in the panel wouldn't it?

**Comment by jjohns71** [comment]
> But that would allow everything in the panel wouldn't it?

## Steps to follow for setting global rules through the GUI 

For the steps below we will use an [example website](http://digg.com/video/free-climber-pass) which has a youtube video embedded on the page.

**Step 1.**
From the uMatrix panel in the very top left corner select the blue dropdown which should show the website domain you are currently on and select '*' instead of the domain you are currently on.
![step01](https://cloud.githubusercontent.com/assets/6795795/21402745/eb69e20e-c787-11e6-9ff2-cad84ef8f0c3.png)

**Step 2.**
Select the rules you want to allow from the 3rd party domain.
![step02](https://cloud.githubusercontent.com/assets/6795795/21403001/1785168c-c789-11e6-9dc0-ab406ecfc4b3.png)

**Step 3.**
Click the unlocked padlock icon from the uMatrix panel to permanently save the new rules you have just allowed.
![step03a](https://cloud.githubusercontent.com/assets/6795795/21403353/70c21622-c78a-11e6-82a1-04b7fd42e409.png)


## **Alternative Step 3. Procedure**


Open the uMatrix dashboard and click on the 'My rules' tab. Make your temporary rules permanent by committing them by clicking on the '<- Commit' button.**
![step03b](https://cloud.githubusercontent.com/assets/6795795/21403357/754950a2-c78a-11e6-936e-a956b05afb64.png)
_This is an alternative to clicking the padlock icon from the uMatrix panel to make rules permanent._


**Step 4.**
Refresh the [example website](http://digg.com/video/free-climber-pass)

**Step 5.**
Repeat steps 1-5 until the video fully loads.
![step04](https://cloud.githubusercontent.com/assets/6795795/21402788/0fbbb3a8-c788-11e6-819f-dbe18713d235.png)
_In the screenshot above scripts for domains 'www.youtube.com' & 's.ytimage.com' and frames for 'www.youtube.com' have now been allowed._

### Rules you set following the steps above should now be global and apply to all websites.

**Comment by k-h** [comment]
Thanks.

BTW I should add here that youtube.com is a pain because you have to allow it first, then you reload and you get the ytimg.com which you have to allow, then you have to reload and you get googlevideo.com which again you have to allow.  Phew.

**Comment by aeris** [comment]
Hello people !

For security/privacy concerns, you don’t want to directly allow youtube/google/cloudflare from anywhere, but currently, because of the behaviour reported by @k-h, you have to refresh your page multiple times. 5× for ReCaptcha for example, and the last refresh is only possible *after* you fill the captcha and validate the form and then you got the last XHR request pointing to another domain.

Would be interesting to have a dropdown menu with pre-filled temporary rules (ReCaptcha, Youtube…) to apply on the current page without having real blocked request to corresponding domains, reducing refresh needed to 1.

**Comment by ibotty** [comment]
Aeris is right. Many don't want to allow youtube globally. It would be great, if there were a dropdown that will add some predefined rules to the active scope. I opened a issue about that: #702.

**Comment by gorhill** [comment]
@jjohns71 gave the proper answer.
