### ISSUE TITLE
Synology NAS - Interface Slowdown

### ISSUE THREAD

**Issue by californicated** [gorhill/uMatrix#692]
I'm using a NAS from Synology (DS216 Play) with the most recent Disk Station Manger 6.0. 

After installing uMatrix on my desktop computer, the interface experiences a huge slowdown. Recreating the issue requires a Synology NAS, other than that the steps are pretty simple:

1. Go the xyz.quickconnect.to, where xyz is the name you've setup to address the little machine.
2. Login

(Step 1 and 2 already take longer than without uMatrix)

3. You'll already notice the widgets to load way longer than before. Now try to open an app or the settings. What usually requires a second, might need half a minute. Also streaming music sometimes get's laggy. 

I've already tried to set an exception for quickconnect.to. uMatrix shows green, but the issue is still there. It might be interesting, that I experience a pretty similar behavior when trying NoScript.

**Comment by californicated** [comment]
I forgot to mention that the issue affects Chrome v55 as well as Firefox v50. Both as x64 version.

**Comment by gorhill** [comment]
You will have to investigate yourself, I am in no position to investigate this. Aside disabling uMatrix, did you also disable user agent spoofing, referrer spoofing and strict HTTPS switches?

**Comment by californicated** [comment]
All three switches are turned off as per default. Still thanks for your reply!

**Comment by levicki** [comment]
Does it help if you put the URL in matrix-off?

**Comment by JoelAzaria** [comment]
I have little to add except that I use uMatrix for a long time have/use about a dozen Synology NASs and I do not see this behavior.
Granted it's been a long time since I've touched a Synology box *without* umatrix running, but I have no such issues in DSM UI *with* umatrix.

One difference is that I do NOT use quickconnect.  Perhaps try accessing DSM directly and see if you still have a problem.
