### ISSUE TITLE
uMatrix controls cut off

### ISSUE THREAD

**Issue by beefstew** [gorhill/uMatrix#694]
In Google Chrome on Mac OS X (version 55.0.2883.95 (Official Build) (64-bit)), the top controls of uMatrix are often cut off when I click the extension icon.

http://imgur.com/a/IKWXG

I can't figure out what causes it, so no steps to reproduce. But this small rendering occurs quite frequently.

The list of sites scrolls in the displayed area with the mouse wheel and you can enable domains as usual (for the sites that are visible). However, the padlock and reload buttons are inaccessible.

Usually, if you keep clicking the extension icon (6-20 times), something will sort out the layout problem and display correctly. None of resizing the window, showing other extensions, or switching tabs seems to cause the correct rendering.

http://imgur.com/a/lyD5o

**Comment by berlinjunker** [comment]
I also seem to have the same problem.

Specs:

* Resolution of 3840x2160 - scaled to 2560x1440
* MacOS Sierra 10.12.1
* Chrome 55.0.2883.95

Even though, the issue has been already posted, I doubt that this is supposed to be an chromium issue.

Related post: [https://github.com/gorhill/uMatrix/issues/114](https://github.com/gorhill/uMatrix/issues/114)

On my Macbook Air 13" with a 100% scaling, I haven't seen this issue at all so my guess is that only scaled displays (retina displays) are affected.

**Comment by beefstew** [comment]
This bug occurs for me on an early 2011 MacBook Pro 15" without Retina and resolution set to "Default for display", so I'm not sure it's scaling related.

**Comment by berlinjunker** [comment]
Are you sure, that you are using a non-retina display? Because your screenshots looks high-res to me. And resolutionwise, I would say that it is in fact a Hi-Res screenshot.

**Comment by snafuy** [comment]
Confirm that this happens regardless of display resolution. Affects both my Pre-retina MacBook and TouchBar MBP, on the internal screen, external monitor, or HDTV.

**Comment by beefstew** [comment]
I use both a 2011 non-Retina MacBook Pro and a mid-2015 Retina MacBook Pro. It occurs in Chrome on both.

**Comment by gorhill** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=428044

**Comment by ddraws** [comment]
This (rarely) happens in Firefox for me, uBO as well. but it only happened it regular edition. So far it has not happened in Nightly. Fixes itself after restarting browser. Removing and readding the addon didn't help.

**Comment by altunyurt** [comment]
Same on Firefox 53b

![umatrix](https://cloud.githubusercontent.com/assets/126674/24237996/55e7d6ce-0fb1-11e7-8c70-ac81453afde7.png)

**Comment by gorhill** [comment]
> Same on Firefox 53b

Is it occasional or always like this?

**Comment by sgreadly** [comment]
This is by far the most annoying bug. It happens on both my Macbook Pro and MacbookAir, on several Chrome versions (as back as 1 year at least and up to the latest version).

Again it's really hard to troubleshoot because it's random, but it happens on just about every website. And you have to click to expand it again say 10 - 20 times to get it to finally pop up properly. Do it again once or twice and the problem happens again.

I tried refreshing the page, or moving the content up/down a bit, but that doesn't really help. And I don't believe it is related to the content, because even simple sites like google.co.nz can have this issue. 

As an example & quick test. Even on this page as I type, I tried expanding it and the popup was successful 3 times. The 4th time, the problem happened, and I took a screenshot.

I'm happy to help troubleshooting though if there's anything you need.

Ta.


![screen shot 2017-03-25 at 3 41 24 pm](https://cloud.githubusercontent.com/assets/1705194/24318868/dc76e5b0-1171-11e7-987c-52cd70dab859.png)

**Comment by zmwangx** [comment]
It's been this way for ages IIRC and happens for my other extensions too. A link to the Chromium bug report has already been posted above: 
https://bugs.chromium.org/p/chromium/issues/detail?id=428044. I doubt anything can be done here.

**Comment by gorhill** [comment]
If ever there was a workaround possible, this is not something I am in a position to investigate. Someone with dev skills and a MacOS will have to fiddle with HTML/JS to find out if something can be done to work around the issue.

**Comment by altunyurt** [comment]
@gorhill while it was happening, it wasn't everytime.  I'm running ff53b6 on linux mint right now and i don't remembr it occuring since i posted the previous comment, maybe the ff updates helped.  
 
It now works on the same page in my prev. comment 
![scrshot](https://cloud.githubusercontent.com/assets/126674/24498624/b0ab40b4-1547-11e7-8653-e9dbac1e4a96.png)

**Comment by gson88** [comment]
I have the same issue on my mac.
Maybe you can add the workaround posted in the chromium bug report?
Setting display: none; then display: block; on the body-element works for me when testing.

**Comment by gorhill** [comment]
Best is if someone with dev skills try the workaround, I do not have a mac, I can't test whether that works. Also, this would have to be tested to find out if such workaround affects negatively uMatrix on other platforms.

**Comment by gson88** [comment]
I only tested it by inspecting the elements and changing the css from the inspector. 
I'm trying to find where to put it, not very experienced in browser extensions.

**Comment by gorhill** [comment]
Ok how about..

Add `style="display: none;"` in [this div](https://github.com/gorhill/uMatrix/blob/master/src/popup.html#L60), result:

    <div class="paneContent" style="display: none;">

Then add the following line:

    document.querySelector('.paneContent').style.removeProperty('display');

At this point in the source code:
https://github.com/gorhill/uMatrix/blob/master/src/js/popup.js#L1269

**Comment by gson88** [comment]
It doesn't help unfortunately. No difference.
Is there an event for when the animation is done?

**Comment by gorhill** [comment]
The animation is from MacOS, it's completely outside of uMatrix, and probably the browser I suppose.

**Comment by gson88** [comment]
The most consistent "fix" seems to be this
`setTimeout(function(){
		document.body.style.display = "none";
		
		setTimeout(function(){
			document.body.style.display = "block";
		}, 5);
	}, 300);`
But it makes the whole popup flash a little bit after opening. Not a pretty fix. And I'm not sure how it looks on windows.

**Comment by gorhill** [comment]
One thing I am curious about is if the `resize` event is fired when the popup window size is animated: <https://developer.mozilla.org/en-US/docs/Web/Events/resize>. Is it something you can verify? Like just adding the code below is see what is reported at the console:

    window.addEventListener('resize', function(ev) {
        console.log(window.innerHeight);
    });

**Comment by gson88** [comment]
Yes it is 👍  
It's called twice, once with height 208 (which seems to be the min-height), and then once with the height of the finished popup. 
When the bug happens, it still says it's for instance 600px.

**Comment by gorhill** [comment]
Ok, I would like to understand better by seeing what is reported at the console.

Let's use this line for logging purpose inside the event handler:

    console.log(window.innerWidth + 'x' + window.innerHeight, document.documentElement.clientWidth + 'x' + document.documentElement.clientHeight);

Let's use this site as test case (I picked it because it causes the uMatrix popup to need vertical scrollbar when the rows are not collapsed):

    `http://www.tomshardware.com/`

This is what I get a Chromium dev console for the popup:

    538x600 523x600

I would like to see what is outputted for Chrome on Mac OSX.

**Comment by gson88** [comment]
I get 
    416x208 416x208
    523x600 523x600
both when its working and not working.

**Comment by gorhill** [comment]
Ok, we need to try something else, something which highlight the anomalous state when it occurs. How about replacing `document.documentElement` with `document.body`? I get:

    416x208 416x208
    538x600 523x956

**Comment by raylee** [comment]
I have the same problem (OSX/Chrome) and DOM is reporting the wrong values for me as well. If I set the width to the existing width+1, it forces a resize.

Any solution for detecting the anomalous state will likely be on a timeout. Perhaps instead on OSX uMatrix could simply change the size on that timeout. If the problem didn't occur, there will be no noticeable flash, just a tiny resize. If the problem did occur (which seems most of the time now), it'll at least address the issue.

**Comment by gorhill** [comment]
https://github.com/gorhill/uMatrix/issues/694#issuecomment-275261679
