### ISSUE TITLE
[Chrome] garbled content

### ISSUE THREAD

**Issue by Bebef** [gorhill/uMatrix#698]
Using uMatrix in Chrome, web pages will often show garbled content only (see screenshot). Reloading helps most of the time. However, sometimes you have to reload the page several times in order to get it displayed correctly.

Environment:
- Windows 10 Pro x64 version 1511 Build 10586.713
- Chrome Version 55.0.2883.87 m (64-bit)
- uMatrix 0.9.3.6 and 0.9.9b2

The problem will occur as soon as I have uMatrix installed, even when starting with a blank profile.

## Steps to reproduce the issue
Unfortunately, I can not provide steps to reliably reproduce the issue. However, here is something that _might_ work:

1. on a clean install of Chrome (Windows), install uMatrix
2. Apply those rules: [my-umatrix-rules.txt](https://github.com/gorhill/uMatrix/files/707716/my-umatrix-rules.txt)
3. browse a page you haven't visited before (e.g. http://stackoverflow.com/questions/10268583/downloading-java-jdk-on-linux-via-wget-is-shown-license-page-instead)

If you're lucky this might reproduce this issue. Sorry I can't provide a better, more reliable way to reproduce the issue.

However, I can share some facts:
### Facts
- the issue will occur as soon as uMatrix is enabled, regardless of other extensions installed
- no setting within the extension itself (e.g. privacy or host files) will change the behaviour
- if the issue occurs, reloading the page itself always helps; sometimes one reload is enough, sometimes three, four or even more reloads are needed in order to have a page displayed correctly
- as it seems, once a page is loaded correctly, it will always load correctly in that particular session (you can't go back to a "garbled" version just by hitting F5)
- using `"* * * allow"` as rule, thus effectively disabling uMatrix, won't break pages any further!

So maybe the issue has something to do with rule processing?

![garbled web umatrix](https://cloud.githubusercontent.com/assets/6527854/21976707/5f892370-dbd3-11e6-91e2-2f7bab01c156.png)

**Comment by gorhill** [comment]
> So maybe the issue has something to do with rule processing?

uMatrix merely tells the browser whether to cancel a network request (by evaluating its rules) through the extension API -- it does not care or deal with the content of the document.

**Comment by Atavic** [comment]
@Bebef try changing `matrix-off: behind-the-scene true`

**Comment by Bebef** [comment]
@Atavic `matrix-off: behind-the-scene true` is the default setting. So by "changing" you mean setting it to "false"?

**Comment by Bebef** [comment]
OK, that didn't help...

**Comment by gorhill** [comment]
I never experienced such issue, and no such issue was ever reported. Most likely explanation is that something specific on your side external to uMatrix causing this. Any anti-virus? Your ISP messing up the page headers? (I noticed your link is not https).

**Comment by Atavic** [comment]
Seems like _google chrome_ with addons and _stackoverflow_ have problems .

Particularly, JS errors appear regarding `https://www.adzerk.net/ados.js`
and `https://ssum-sec.casalemedia.com/`

**Comment by hardfalcon** [comment]
I have exactly the same issue with uMatrix in Firefox on Archlinux x86_64. For some reason, most (all) sites using UTF-8 encoding get misdetected as "western encoding" (I suppose this is ISO-8859-1), thus displaying for example German umlauts as garbled text ("ß" gets displayed as "ÃŸ", "ö" as "Ã¶", "ä" as "Ã¤", etc).

It seems to happen when a page gets either loaded the first time or when it gets loaded from cache. When I explicitly reload the page (F5), the content encoding gets detected correctly.

Unfortunately, this does not only occur with HTML content, but also with binary stuff like videos (sometimes resulting in a crash of Firefox, probably due to some flaky demuxer) or PDF files.

I'm yet to find out a possibility to reliably reproduce this bug because it does only occur intermittently - but *when* it occurs, it seemingly affects all new tabs/sites I open, and I have to reload every single new tab/site to get rid of the wrongly detected encoding.
