### ISSUE TITLE
port to firefox?

### ISSUE THREAD

**Issue by q0LoCo** [gorhill/uMatrix#73]
Is there a plan to port uMatrix to firefox?
I wrote a httpsb prototype demo on firefox while waiting uMatrix.
![pic2](https://cloud.githubusercontent.com/assets/9827570/5285929/e70df19e-7b5a-11e4-9edc-ab5454e06425.png)

sorry for my bad english.

**Comment by lewisje** [comment]
Policeman also looks like an extension of this type.

**Comment by DomT4** [comment]
This would be great. I use uBlock on Firefox, but I'm loving the fine-grained control I get from uMatrix in Chromium.

**Comment by vv0909** [comment]
uMatrix is great, definitely looking forward to the Firefox version.

**Comment by asymmetric** [comment]
:+1: , I love uMatrix's interface and fine-grained control capabilities. It's so much better than RP!

**Comment by vdcbb** [comment]
Yes, please bring uMatrix to Firefox. I can't wait.

I considered switching to Chrome just for this app, but I strongly prefer Firefox. So I will hope uMatrix will come to Firefox. And please do include a keyboard shortcut in Firefox for opening the uMatrix popup.

This is one of the coolest apps. Thanks for creating it.

**Comment by hackel** [comment]
Just an FYI--I finally disabled Request Policy once and for all.  µBlock's advanced mode with dynamic filtering seems to cover everything I need.  While a µMatrix port will be nice when it's ready, make sure you check out how awesome µBlock already is!

(sorry for the notification spam)

**Comment by mailinglists35** [comment]
when uMatrix comes to firefox, it will be a hard time to choose between chrome and firefox.
tired of increasing bloatness of google chrome and their apple-like features policy.

**Comment by gorhill** [comment]
Given the amount of users for Policeman (2,417), I don't feel too motivated into taking on this if it's going to be only useful to so few users, given the amount of work.

The reality is that this is a kind of tool which is appealing to very few users compared to RequestPolicy-like tools, which are themselves much less used than more generic blockers. And there is already such tool available for Firefox --  Policeman. So:

- Lot of work
- Very few users (also true for Chromium which never went beyond 20,000)
- An alternative already exists -- Policeman

For now I feel my time would be better spent to make the code more portable -- using uBlock `vAPI`.

**Comment by asherdavidson** [comment]
I agree with much of what you said, but the advantage that uMatrix has over Policeman is that it's much more user friendly. I could block and unblock connections in seconds with uMatrix, while doing the equivalent in Policeman is a pain in the ass.

I would be willing to pay for uMatrix if you ported it to firefox. It's the only plugin that I miss since I ditched chrome.

**Comment by benoit-pierre** [comment]
> I agree with much of what you said, but the advantage that uMatrix has over Policeman is that it's much more user friendly. I could block and unblock connections in seconds with uMatrix, while doing the equivalent in Policeman is a pain in the ass.

This. The number of clicks needed to do anything with Policeman is much higher. Plus the latest version of Policeman is really buggy.

**Comment by tlu1024** [comment]
@gorhill : I understand your reasoning. On the other hand, Noscript has more than 2 million users! Now considering that

- uMatrix offers much more than Noscript
- Noscript is not yet E10s compatible (and it's [unclear](https://bugzilla.mozilla.org/show_bug.cgi?id=1058542#c40) when it will be)
- Firefox users are traditionally more privacy aware than Chrome users

chances are that a Firefox version of uMatrix might get much more attraction than you think. Just my 2 cents ;-)

**Comment by gorhill** [comment]
As said I am working on making the code portable by importing @Deathamns' API abstraction layer (the import was done in such manner as to preserve [history of contributions](https://github.com/gorhill/uMatrix/commits?author=Deathamns)).

This requires a lot of change on uMatrix's side, but once done, a Firefox version could just be a few lines of code away.

**Comment by asherdavidson** [comment]
Oh, that's pretty great! I didn't realize that's what you meant.

**Comment by Faberman** [comment]
Thank you for your work. I'm also waiting for uMatrix for Firefox.
Policeman is not an option. I've tried Policeman and its interface is awful: click here, click there, than click here again, etc. Also uMatrix has additional options for more privacy. And of course uMatrix has its killing feature - genius matrix-style interface, simple and powerful. I have been using NoScript+RequestPolicy for years, but I'll definitely replace those addons with uMatrix.

**Comment by Zement** [comment]
Fantastic work. Thank you!
I would also love to see µMatrix for Firefox. :)

**Comment by josegl** [comment]
great work, I am waiting a firefox port too. policeman is a good alternative, but umatrix is much more userfriendly and requires less clicks to achieve your target.

**Comment by gorhill** [comment]
Fixed in 0.9.0.0.

**Comment by asherdavidson** [comment]
Awesome! It's working great so far! :)

**Comment by excalibur1234** [comment]
these are great news!
thank you very much.

**Comment by githubdbes1** [comment]
mailinglists35 commented on Mar 28
> when uMatrix comes to firefox, it will be a hard
> time to choose between chrome and firefox.
.
Unfortunately it won't.  uMatrix is the #2 browser add-on.  #2 in no way diminishes uMatrix's awesomeness.  I *won't* run my browser without it.  Thank you gorhill!
.
However, there is another . . . browser add-on that (for folks who have at least started to master it) will keep you nailed to Chromium (yes, it is a cross (no offense to Christians) due to some bitch dev decisions.  Lest you think I'm biased, some Firefox devs score a close second in the bitch category.
.
I might be about to make your switch more difficult.
.
.
Drumroll . . .
.
.
The #1 browser add-on (which is not yet cross-platform) is:
.
.
.
.
.
Tabs Outliner
https://chrome.google.com/webstore/detail/tabs-outliner/eggkanocgddhmamlbiijnphhppkpkmkl
.
.
If you let it, this add-on will revolutionize how you use a web browser.
.
.
(And before you prematurely dismiss my contention that Tabs Outliner is the #1 add-on as false, consider for a moment that I breathe the same rarefied air as the other 0.0003% (yes, I did the calculation) of advanced Firefox users who use the Firefox uMatrix add-on (along with some other credentials).)
.
.
So check out Tabs Outliner.  I didn't write all of the above for my own benefit.
.
.
Namaste,
david
.

**Comment by CrisBRM** [comment]
@githubdbes1 That's hardly relevant, but Firefox has had Vertical Tabs / Tree style tab for a while.

**Comment by hackel** [comment]
@githubdbes1 Really don't appreciate the notification spam.  Please don't abuse Github issues.

**Comment by Raavizz** [comment]
> @githubdbes1 : bitch dev

Stop your drama / insulting / bad words / agression.
