### ISSUE TITLE
Specific blocking.

### ISSUE THREAD

**Issue by AratnitY** [gorhill/uMatrix#74]
"I kind of wish there was a way to expand umatrix's window so if there were 4 script requests we could pick which ones to allow/disallow instead of just allowing all 4."

Is this something that can be implemented in the future? Or does chrome not allow for such specific requests?

**Comment by gerg5c42g542g2c54g52c** [comment]
@gorhill is this the recommended way? If one wants to only allow some specific absolutely required scripts coming from a certain domain then one has to use two addons uMatrix and uBlock Origin and set a whitelist rule in uBlock?

Have you thought of adding these few features (granular script blocking, XSS protection, only allow https) that force people to use many addons instead of just uMatrix? It seems completely pointless and insecure to have X addons that all do very similar things.
