### ISSUE TITLE
[Request] User Agent Spoofing Enhancement

### ISSUE THREAD

**Issue by zero77** [gorhill/uMatrix#743]
Instead of changing the user agent every selected number of minutes.

Can you please change the user agent when visiting a new domain or revisiting the same domain after the tap/window has been closed.

Or, use a random time within a certain range like every 0 to 5 minutes, as the current option is very easy for trackers and websites to spot.

Thanks

**Comment by gorhill** [comment]
[CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md):

> **Do not open feature requests.** I just do not have the time.

**Comment by potholiday** [comment]
@gorhill  I have read the readme and thats why I am not opening  a new feature request. I know you dont have time for new feature request but please read this with an open mind and in future if ever you get time please consider this.

I am a biggest fan of [RAS](https://github.com/dillbyrne/random-agent-spoofer) addon especially because of its wide selection of [useragents list from mobiles to desktops and from linux to firefoxOS](https://cloud.githubusercontent.com/assets/2903711/7324733/e0aa7140-eab0-11e4-889d-d1ceb7da9a0f.png) but because of API issue RAS will not be developed further from firefox quantum version onwards. While searcing somebody recommended your addons which can change useragents but dont have the list of useragenst. I would like a similar list of useragents like RAS in uMatrix and believe it would be a good addition for privacy for users.
