### ISSUE TITLE
please update the chrome store with latest release...

### ISSUE THREAD

**Issue by mailinglists35** [gorhill/uMatrix#753]
...so fix for issue https://github.com/gorhill/uMatrix/issues/689 can land in store without having to manually get the github version

**Comment by anewuser** [comment]
Please don't create useless issues like this. Just wait until the extension developers have some free time and then wait until the extension stores review and publish the new versions.

**Comment by gorhill** [comment]
No doubt the bug is detrimental to uMatrix, but I just can hastily push a version for which there is so much [code changes since last version](https://github.com/gorhill/uMatrix/compare/0.9.3.6...master):

> Showing  102 changed files  with 4,175 additions and 3,728 deletions.

I need to be convinced this has all been tested to be sure there is no major regression -- I am the one who will be on the receiving end. I have absolutely no idea how many people are actually using the dev build, so to compensate for this I just wait for enough time to have passed with no new issues opened to be confident a new stable can be released.

**Comment by mailinglists35** [comment]
@gorhill ok i understand; then can you patch the stable version with fix for #689?

chrome 57 stable is already out for a whole month and this means every regular user who installs umatrix is affected.

and that is really annoying and it's happening on about 1/10 of sites I visit using chrome 57

**Comment by gorhill** [comment]
Look at #711. My last commit is marked as "need confirmation". Not a peep since then.

**Comment by uBlock-user** [comment]
Surprisingly, I haven't been able to reproduce the bug for a quite some time since the last Chromium update on v59 fyi.
