### ISSUE TITLE
[v1.0.0 webext] Icon not displayed

### ISSUE THREAD

**Issue by TriMoon** [gorhill/uMatrix#763]
Conforming to https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md,

 1) Due to unsigned extension:
     1) Follow the [instructions at MSC](https://support.mozilla.org/t5/Problems-with-add-ons-plugins-or/Add-on-signing-in-Firefox/ta-p/30262#w_what-are-my-options-if-i-want-to-use-an-unsigned-add-on-advanced-users) to flip the setting `xpinstall.signatures.required` to **false**
 1) Install [uMatrix.webext.xpi](https://github.com/gorhill/uMatrix/releases/tag/1.0.0) v1.0.0
 1) Open Firefox's `customize` page via the `≡` menu, The uMatrix icon will be blank, eg. **not** displayed.

Due to this issue it will be **very hard** for users to organize where they want the icon to be displayed...

Using: FireFox _Developer-Edition_ on Debian 9
`Mozilla/5.0 (X11; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0 ID:20170414074709 CSet: 189ed7b2306fcf0a7683df6959b78fdb94bb34e7`

**Comment by gorhill** [comment]
I could reproduce when I drag-n-dropped the xpi file into Nightly. However I can't reproduce once I restart the browser.

**Comment by gorhill** [comment]
I can't reproduce when starting Nightly.

I can reproduce all the time when disabling then enabling the extension. There is no error reported at the browser console, so I don't know what the issue is. uBO/webext does not suffer the issue.

**Comment by gorhill** [comment]
Spotted at bugzilla: [blank browserAction with extensions.webextensions.remote=true](https://bugzilla.mozilla.org/show_bug.cgi?id=1357729).

**Comment by TerraX-net** [comment]
I created that bugzilla entry: The dropdown bubble is empty when extensions.webextensions.remote=true.

**But this bug here is different.**
This happens with extensions.webextensions.remote=false.
If I open a new tab with Ctrl+T, uMatrix does not have an icon. If I then type in about:newtab and press enter, uMatrix gets an icon and recognizes newtab.about-scheme.
![screenshot_20170501_123545](https://cloud.githubusercontent.com/assets/17962859/25578019/1a264066-2e6b-11e7-8014-9cebef52f1a8.png)
