### ISSUE TITLE
can't quit Firefox

### ISSUE THREAD

**Issue by lnxpgn** [gorhill/uMatrix#779]
Environment:
uMatrix: 0.9.3.6
Firefox: 53.0
MacOS: Sierra 10.12.4

Sometimes open a blank privacy window, In more cases need to open a page in a privacy window, then can't quit Firefox, can't pop-up "About Firefox" window, can't open "Preferences" tab, other Firefox functions work. If I want to quit Firefox, need to kill Firefox process in "Activity Monitor".

If just oepn non-privacy windows, it seems no problems. if disable uMatrix add-on, this issue disappears.

This issue wasn't only  appear in Firefox 53, also in earlier several versions as I knew.

**Comment by gorhill** [comment]
No hint of you having investigated your ruleset, no hint of your ruleset, no hint that you investigated other extensions to rule out another extension being involved in your issue, no hint about your browser settings including tampering with `about:config`, no hint whether the issue is solved with a new profile. You will have to investigate yourself on your side, so far it's only you reporting such issue so this hints at something specific on your side causing this.

Please read carefully [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md) -- I expect _advanced_ users of uMatrix to be more thorough in their reporting.

**Comment by 5t3f4n** [comment]
I have this issue too, and have had it for as long as I can remember.
It's been present since I was running El Capitan and whatever version of Firefox/uMatrix I was running then. I tried troubleshooting it back then (clean install of macOS + Firefox + uMatrix) but I could not pinpoint what causes it, it appears sporadically.

When it happens, most keyboard shortcuts stop working, for example <kbd>⌘</kbd>+<kbd>Q</kbd> (Quit) as well as some menu bar items. I have to quit by right-clicking the Dock icon when this happens.

Aside from having done a bit more troubleshooting compared to OP, there is little I can add besides a "me too" unfortunately.

**Comment by gorhill** [comment]
Another basic thing to do is to look at the browser console.
