### ISSUE TITLE
uMatrix UI unusable with dark background

### ISSUE THREAD

**Issue by unexistance** [gorhill/uMatrix#787]
see https://imgur.com/a/tiSbm

Browser : Firefox
Settings : https://imgur.com/a/zfDFU

I can't be sure if anything I click is effective or not, since there's no visible change in the UI

**Comment by Atavic** [comment]
Which firefox version?

https://i.imgur.com/vnTPFKh.png

**Comment by unexistance** [comment]
ESR : 45.9.0

**Comment by gorhill** [comment]
Unable to reproduce with Nightly, FF54 and uMatrix 1.0.0.

**Comment by Atavic** [comment]
No issue in Palemoon, @unexistance may have something messing with Firefox UI, as normally uMatrix UI doesn't follow the background mods for the rendered pages.

**Comment by unexistance** [comment]
yes I'm using custom background / foreground color in all website, in which @Atavic confirms uMatrix does not follow

May I suggest a change in the font? like bold if enabled & strike-out if disabled? or something to that effect

**Comment by gorhill** [comment]
> just set Firefox Content | Color settings are per https://imgur.com/a/zfDFU

I did not notice the "Always" for "Override the colors specified by the page with your selections above:". I can reproduce if I select "Always".

I will be straightforward: if you ask Firefox to override colors of all web pages (which is what uMatrix popup panel is), then you are asking for trouble, not just with uMatrix, but with probably a lot of other web pages. I just do not have the inclination and especially that sort of free time to "fix" this assuming one would agree in the first place the issue is with uMatrix. Declined.

**Comment by Atavic** [comment]
If you want dark background you have some options as using an addon as Stylish or Greasemonkey.

**Comment by unexistance** [comment]
> then you are asking for trouble, not just with uMatrix, but with probably a lot of other web pages. I just do not have the inclination and especially that sort of free time to "fix" this assuming one would agree in the first place the issue is with uMatrix.
I actually have NO trouble with other website, since it's my OWN decision to reduce web distraction this way

Guess it's not a fix, just usability request

**Comment by benoit-pierre** [comment]
A better solution if you want light text on a dark background then using the Firefox settings is this add-on: [Dark Background and Light Text](https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/).
