### ISSUE TITLE
XHR's by other browser extensions doesn't always show up in the matrix

### ISSUE THREAD

**Issue by caspervk** [gorhill/uMatrix#795]
Reddit Enhancement Suite (RES) makes XHR's to imgur.com among others to show expandos with extended functionality on reddit.com. Unfortunately, imgur.com doesn't show up in the matrix, and as such, can't be allowed. When matrix filtering is disabled for the `*` scope, the RES errors disappear.

Sometimes the imgur.com domain _does_ show up in the matrix, but without any indication of XHR requests being made (the field is simply empty).

The issue is not limited to imgur.com, but also appears to be happening with wikipedia.org and giphy.com expandos using the RES extension.

The error can be reproduced by installing RES and uMatrix - both with their default settings - and visiting reddit.com. The browser's JS console should be spammed with `Error: Error in target's "ajax" handler: NetworkError when attempting to fetch resource.`.

**Comment by caspervk** [comment]
Instead of disabling filtering for the `*` scope the error can also be resolved by manually adding `reddit.com imgur.com xhr allow` as a rule. However, as RES supports expandos for over 50 different domains, the task of adding these to uMatrix manually would be quite cumbersome compared to simply ticking the XHR-field if it could be fixed to show up.

**Comment by gorhill** [comment]
You are not providing details about what browser you are talking about.

I will assume a Chromium-based browser, and this is a browser behavior -- it won't disclose network request by an extension to another extension webRequest listeners.

**Comment by caspervk** [comment]
I'm using Firefox. How come uMatrix is able to block the request then?

**Comment by caspervk** [comment]
Is there any way to allow XHR for other extensions? The alternative is allowing XHR for the `*`.

**Comment by Remu-rin** [comment]
Try `c3b0e9a3-eec7-439d-be07-ac4cf08de79e.moz-extension-scheme * xhr allow` or use logger.


![-1](https://cloud.githubusercontent.com/assets/28995228/26531809/c89df13e-440a-11e7-9c5c-1ed13f70c82c.png)

**Comment by caspervk** [comment]
Thank you! This resolved the issue completely.

Of course I couldn't find any blocked requests in the logger, I was looking under the specific tab instead of All!

**Comment by Alamei** [comment]
Out of curiosity, what changed in the code between 0.9.x and 1.0 that caused the RES addon XHR requests to be blocked by default when they were formerly allowed? My temporary workaround for this issue (before I found this thread and saw the solution) was to just roll back to 0.9.3.6, so it must have been allowing the requests through.

Since this particular behavior adjustment isn't mentioned in the changelog (and may have been unintentional), there are likely some users confused as to why certain addons are suddenly no longer functioning correctly, and it's pretty easy to miss that fact that the requests are even being filtered because we're trying to troubleshoot the logs on a specific tab instead of the 'All' log, judging by the fact that both caspervk and I made the same mistake.

Is there by any chance a straightforward way to integrate the filtered addon requests into the main matrix panel to allow them to be approved without hunting through the logs? I feel like the log solution is a bit complex even for the generally technically-inclined uMatrix userbase to guess without at least a hint at where to look.

**Comment by gorhill** [comment]
uMatrix blocks according to its ruleset, I can't think of anything special with regard to behind-the-scene requests between 0.9.3.6 and 1.0.0. Unlike uBO, uMatrix does not put obstacle to block behind-the-scene requests, the ruleset decides -- this includes _switch_ rules such as `matrix-off`. I shouldn't be needed to investigate  anyone's ruleset, this is the first thing to look at when diagnosing issues, including using the logger.

**Comment by caspervk** [comment]
The logger is certainly a valuable tool when diagnosing issues; that said, the user experience could be improved significantly by integrating the filtered addon requests into the main matrix panel, as Alamei stated. The nature of addons, however, could prove this task difficult as it can be complicated to figure out which tab causes an addon to make requests.

Instead, as one already puts complete trust in ones browser extensions, I think it would be beneficial to allow all network requests made by extensions by default.
Is there any way to `matrix-off` for all extensions with one simple rule?

**Comment by Alamei** [comment]
I agree with caspervk that an option to allow all extension requests (either via a toggle in the settings or a single rule) might be an easier solution than displaying the extension requests into the matrix panel. It would essentially allow users to choose between the 1.0.0 behavior and the 0.9.x behavior

That said, it sounds like the behavior change disallowing the requests in 1.0.0 wasn't intentional, so a new setting may be unnecessary if a future patch will revert to the 0.9.x behavior of allowing extension requests through automatically anyway.
