### ISSUE TITLE
Default Namespace

### ISSUE THREAD

**Issue by temporaryaccount** [gorhill/uMatrix#821]
I'd like to have a predictable default choice of the automatically selected namespace. Currently you can easily reproduce this issue:

1. Open https://addons.mozilla.org/en-US/firefox/addon/umatrix/
2. Open the uMatrix window, select the lowest possible namespace (which is addons.mozilla.org)
3. Allow mozilla.net host to script, close the tab
4. Open https://en.wikipedia.org/wiki/Firefox
5. Open the uMatrix window, the lowest possible namespace will be selected for you (en.wikipedia.org) because we did that for addons.mozilla.org
6. Select an upper namespace (wikipedia.org), make some changes, close the tab
7. Open https://addons.mozilla.org/en-US/firefox/addon/umatrix/ (again)
8. Open the uMatrix window and you can see that now the namespace is mozilla.org (not addons.mozilla.org) because we have selected an upper namespace for wikipedia for some reason it also affected here
9. Also observe an (arguably) bug: the whitelisted mozilla.net is now in red (because we are now in the mozilla.org namespace), but the scripts are in fact allowed (because it is whitelisted in addons.mozilla.org namespace where we are located now)

My suggestion: no matter what always default to the lowest possible namespace, let the user "move up" if he wants to for the particular tab, but don't save the choice for the other tabs.

**Comment by gorhill** [comment]
> Also observe an (arguably) bug: the whitelisted mozilla.net is now in red (because we are now in the mozilla.org namespace), but the scripts are in fact allowed

Not a bug, by design: the matrix shows you the rule for the current scope. It make no sense to show the rules for the scope above, that would be just absolutely incomprehensible and unusable.

> no matter what always default to the lowest possible namespace, let the user "move up" if he wants to for the particular tab, but don't save the choice for the other tabs.

uMatrix remembers the last scope ("namespace") you selected, and pick this one by default. In step 6, you went base domain name level, hence uMatrix starts to use this as the default. This is true also for the global scope, if you pick the global scope, uMatrix will keep using it as the default until you change it (some people might prefer working only in the global scope). TL;DR uMatrix remembers your last choice and use this as the default, when everything is considered, this is the best approach since it doesn't require uMatrix to "guess" what the user want, it's predictable.

**Comment by gorhill** [comment]
I am having second thoughts -- there used to be a drop list in setting in HTTPSB to select the default scope level. I got rid of this with uMatrix because I wanted to keep the amount of settings to a minimum. I am undecided as to whether it would be good to bring in back. I will keep the issue open for a while until I decide.

**Comment by ruv** [comment]
The main issue is that the current behavior is not predictable (if you don't know about it). When you open uMatrix, it is connected to the current tab (and domain), and you don't expect that the changing domain from another tab (it is not obvious that you actually changing global scope level) will affect level in this tab too.

**Comment by gorhill** [comment]
> you don't expect that the changing domain from another tab (it is not obvious that you are actually changing the global default scope level) will affect the level in this tab too.

Ok, good point. I will restore the ability to set default scope in _Settings_: global, base domain, or page hostname.

**Comment by ruv** [comment]
Another way to implement changing scopes is to use logic of radio buttons, with different display form.

The three state for developer.mozilla.org domain can look something like:

**developer.mozilla.org** * — full domain name is selected
developer.**mozilla.org** * — second level domain is selected
developer.mozilla.org **`*`** — any domain is selected

So, for this case we have logically three parts: "developer" "mozilla.org" and `*`. But when "developer" is selected, the full domain name should be displayed as selected.
Although, I don't sure that star after name is enough understandable.

Unchecked part can be be shown as gray (or not so contrastively).
A screenshot from Stylus addon: ![image](https://user-images.githubusercontent.com/2678296/33029779-88b69918-ce2a-11e7-8aad-115a3c19b780.png)

**Comment by uBlock-user** [comment]
The eraser button doesn't work after clicking on global scope button (*), so you can't revert that change from the UI.

**Comment by gorhill** [comment]
It seems the buttons work, but their visual are not properly updated. I will investigate, hopefully a trivial fix I can push asap.

**Comment by uBlock-user** [comment]
Thanks for the quick fix, and yeah missed one more namely "Revert all temporary changes"

**Comment by gorhill** [comment]
> one more namely "Revert all temporary changes"

That one was never disabled, it applies to all temporary rules, including the ones not seen -- the others apply to the temporary rules in the current matrix.

**Comment by uBlock-user** [comment]
okay thanks.

Can you do something about the white layer that is added on top of sub-domains in the POP UI ?

Here's the pic below - 

!()[https://i.imgur.com/Gy17slm.png]

That white layer looks very odd and disturbing to me.

**Comment by theDuckIsAlive** [comment]
@uBlock-user 
That's intentionally done to show the `Default scope level` (Site, Domain or *).
If you don't like it, go to  `uMatrix Dashboard > Settings`  and  set the  `Default scope level`:  to `Site`.

@gorhill
there is still some UI DOM refresh problems
- visit some sites (wikipedia.org, mozilla.org ....) 
- open the uMatrix Dashboard
- open the uMatrix window (the Scope is: behind-the-scene)

Even if we're in the `behind-the-scene` scope, you can see that wikipedia.org, mozilla.org .... are listed in the UI.

**Comment by uBlock-user** [comment]
@theDuckIsAlive I'm already aware of that and I don't want to set it scope level to `site` because then I would have to create rules per sub-domain, which is ridiculous as there can be lots of them.

**Comment by gorhill** [comment]
@theDuckIsAlive 

> Even if we're in the `behind-the-scene` scope, you can see that wikipedia.org, mozilla.org

Because network requests to these sites were made i the behind-the-scene scope, so the connections are reported there. Typically favicons are fetched from behind-the-scene on Firefox. In any case, use the logger, it will show you what is requested from behind-the-scene.

**Comment by gorhill** [comment]
@uBlock-user That is the new scope selector, what you are asking is to go back to the ancient, more cumbersome one -- which of course won't happen.

**Comment by uBlock-user** [comment]
@gorhill I'm not asking you to go back, I'm asking you to remove the white layer only, can you please do that ? clicking once should set sub-domain then again to > domain  and then again to > global, not white CSS layer on it, that's all.

**Comment by gorhill** [comment]
There is no white layer. In your picture, there is only `www.` not being selected, hence it shows as being disabled, pale gray.

**Comment by uBlock-user** [comment]
![](https://i.imgur.com/247md5Z.png)

The red arrow pointing towards the white border, can you see that ? That one.

**Comment by gorhill** [comment]
The local scope is `ghacks.net`, that is why the `www.` part is shown as disabled. If the local scope was `www.ghacks.net`, the `www.` part would not be disabled. How would you suggest to show the non-active part of the local scope?

**Comment by uBlock-user** [comment]
> How would you suggest to present the non-active part of the local scope?

Just remove the non-active part perhaps, if the setting is set to `Domain` and if the person browses to the website's sub-domain, then don't show the sub-domain scope at all, show the domain scope instead because the domain is set in the setting instead of showing the sub-domain disabled.

**Comment by gorhill** [comment]
> then don't show the sub-domain scope at all disabled or not disabled

Of course not, someone might want to actually select a narrower scope to work on a ruleset at that level (for example I might want to set rules specific to `groups.google.com`). That is the point of the new scope selector, to quickly select any possible scope from top to bottom.

**Comment by uBlock-user** [comment]
>  I might want to set rules specific to groups.google.com).

Then do it manually as the setting to `Domain` is set by default in this hypothetical case.

**Comment by gorhill** [comment]
Look, I won't change what is there, I was merely trying to make you see the point of the new scope selector. So we will have to agree to disagree -- your sole argument currently is to remove key functionality **for everybody** because it _"looks very odd and disturbing **to me**"_. So let's leave at that please.

**Comment by uBlock-user** [comment]
It's not just `looks very odd and disturbing to me` it rather confuses me and I end up creating rules for the wrong scope, but then again, it's about me as you say, so I tried to convince and I know you're not gonna change but I tried, so yeah lets leave it at that.

**Comment by gorhill** [comment]
I am open to more feedback from more users. Removing the ability to select a narrower scope would be a downgrade from before, this has always been possible.

**Comment by theDuckIsAlive** [comment]
@gorhill
:(   
No. Please not !

Selecting the scope (sub-domain, domain or even a tld) just by clicking the scope field **fits exactly the uMatrix way.** ..... It's a move in a right direction and user friendly.

I think his problem is more a question of appearance, not usability.
... may be you can make him happy by using some shades of blue color (like #7788EE) instead of graying it out.

**Comment by uBlock-user** [comment]
> Removing the ability to select a narrower scope would be a downgrade from before, this has always been possible.

Again, I never said that, why do you keep mis-understanding me ? What I said/meant is removing the ability to **automatically** display the sub-domain scope (disabled or not) when a person who has set the domain scope to **Domain** via the` dashboard.html` and **happens** to visit a sub-domain of a domain. Keep it manual, so if he wants to see the sub-domain scope he has to set it himself.

Is that clear enough for you ?  If not, then forget it. I can't be anymore crystal clear any further.

**Comment by Remu-rin** [comment]
> Selecting the scope (sub-domain, domain or **even a tld**)

By the way, is that intentional? Result is `com destination type action` rules.
![-1](https://user-images.githubusercontent.com/28995228/33213337-f9fca2c2-d148-11e7-9f78-3c0eed9628db.png)

**Comment by gorhill** [comment]
Yes, I didn't see the point of forbidding it in the end with the new scope selector, though before I was forbidding it, one of the reason was not to make the drop down filled with what would probably a rarely used entry. But with the redesigned selector, it comes for free really.

**Comment by ArchangeGabriel** [comment]
@uBlock-user I want to have the default scope as Domain (because that’s what is the most useful generally) but still be able to have the subdomain available just at one click.

However I agree that this is quite ugly, but that’s also my whole take about uMatrix UI. That being said, I must admit I’m not an UI designer, and I have no ideas on how this could be made better. And I care more about its functionalities than it’s UI prettiness. Maybe just change the text color rather than the background one regarding this specific issue? Something like that (very rough draft):
![test](https://user-images.githubusercontent.com/490531/33232281-9d402b10-d203-11e7-81e2-45e4b7317cd0.png)

**Comment by pwd-github** [comment]
I think just changing the colour of the text as per what @ArchangeGabriel has done with his mockup is a very good and much cleaner idea. 

I would also suggest either using ``div {
    cursor:col-resize;
}`` or ``div {
    cursor:zoom-in;
}`` when making the scope smaller and ``div {
    cursor:zoom-out;
}`` when making the scope bigger to more clearly illustrate the functionality.

**Comment by gorhill** [comment]
> I think just changing the colour of the text as per what @ArchangeGabriel has done with his mockup is a very good and much cleaner idea.

I disagree. There must be no mistake as to which scope is currently in effect, the less ambiguous the better. uMatrix emphasizes a lot of at-a-glance approach, and for this it's important that it's obvious which scope is currently in effect.

**Comment by uBlock-user** [comment]
@ArchangeGabriel well how would telling me that would help ? I already made my peace with the issue I have, you should tell that to gorhill rather if you want to further extrapolate on this issue.

**Comment by gcb** [comment]
IMHO, the old dropdown was OK

The only problem there was that it was cryptic. Now there are toggle buttons, that are still cryptic. Well, only for subhostnames. The `*` at least is pretty clear now 👍

**Comment by ruv** [comment]
> Now there are toggle buttons, that are still cryptic.
@gcb, do you mean the shown state or the behavior (i.e. interaction for changing state).

@gorhill, one additional idea regarding interaction. In terms of radio-button (and internal logic) we have set of the options and only one of them can be checked (i.e. has the "checked" state). When you click on the option that is already checked — nothing is happening. 

Perhaps for this special control element (that didn't look like classic radio-button), it will be more usable if the option at the right becomes checked when the user clicks on the option that is already checked. If no option at the right (i.e. in case of `*`) , the most left option becomes checked.

**Comment by gcb** [comment]
@ruv I meant both. A dropdown is perfectly fine UX element for both showing the current state and showing that there are options. But it must at least look like a dropdown.

IMHO the old dropdown was perfect, it just didn't look like a dropdown, and that was the source of all this mess. And instead of just making it look like a dropdown (i sent a patch, it was literally 1 line of CSS to show a down arrow!) we went down this rabbit hole of inventing a new UX element, that is a cryptic as a dropdown that doesn't look like a dropdown.

You can think of the functionality of a dropdown, when placed on a top level like this, as being the same as tabs, but using less space. It shows you that there are more options, but that the currently selected one is dictating the content you are seeing.
