### ISSUE TITLE
Blocked images download but only briefly display when loaded directly

### ISSUE THREAD

**Issue by Hyundy** [gorhill/uMatrix#822]
Example URL: http://coloringtop.com/sites/default/files/5crxe5bca.jpg

uMatrix 1.1.6 Firefox 58b4

I think this behavior change corresponds with the move to WebExtenions.

Before, if your ruleset had images blocked, that image would download and display. Now, you can see the image download and show for a split second before a tiny white box displays. You must set an allow rule to view the image. 

I hope the previous behavior can be returned to. It is still how uBo works with blocked images.

**Comment by gorhill** [comment]
As per logger, the browser make a request of type `main_frame` (alias `doc`) to the remote server for the image, so uMatrix filters according to the `doc` type, not `image` type. Se essentially uMatrix filters according to what the browser feed it through the webRequest API.

Upon arrival, the resource is transformed into an `img` tag into a document by the browser, this is where something needs fixing in uMatrix, the image should not be collapsed by uMatrix, because it was not blocked.

**Comment by gorhill** [comment]
This was fixed with code change in commit 73c8da05b759.
