### ISSUE TITLE
uMatrix dropdown renders as empty and inactive

### ISSUE THREAD

**Issue by mspielberg** [gorhill/uMatrix#840]
Firefox 57.0
uMatrix 1.1.10

uMatrix UI renders as empty on the site https://www.topgearleather.com/
UI buttons are also unresponsive, except the settings gear, which responds correctly.

See screenshot:
https://imgur.com/a/GXv58

I've disabled all my other FF extensions with no change in the result.

**Comment by ImSpecial** [comment]
I get this too, when I start my browser (FF 57.0) and my homepage loads (DDG) it shows as if it's disabled, if I refresh the page it appears to work again.

On a fresh boot.
https://i.imgur.com/RHFvB45.png

Refreshed the page.
https://i.imgur.com/rvepqgL.png

I want to say this all started happening with either v1.1.8 or v1.1.10.

**Comment by gorhill** [comment]
Unable to reproduce:

![a](https://user-images.githubusercontent.com/585534/33223885-10df83fe-d132-11e7-83ac-4b6859e36be7.png)

**Comment by gorhill** [comment]
> when I start my browser (FF 57.0) and my homepage loads (DDG) it shows as if it's disabled

That is "normal", there is no guarantee that uMatrix will load before a page load when the browser is launched. This is a browser issue: <https://bugzilla.mozilla.org/show_bug.cgi?id=1418030>.

**Comment by gorhill** [comment]
@mspielberg Did you start uMatrix **after** the page was already loaded?

**Comment by gorhill** [comment]
By the look of the popup panel, uMatrix was not able to find the tab for which it is brought up, this result in no data filling the popup. The next dev build will be more explicit about this, there will be a message that no web page data could be found, rather than a visually broken popup.

Still, I can't reproduce this specific issue.

**Comment by mspielberg** [comment]
I've had uMatrix installed for at least the last few days, so no, I did not start uMatrix after page load. I tried reloading via F5, but I don't recall if I tried opening a new tab, new window, restarting Firefox completely, etc. I'll investigate and see if I can reproduce in a fresh browser instance.

**Comment by T-vK** [comment]
As soon as I log into web.whatsapp.com uMatrix shows "No web page found". Before I scan the QR code to login, it works fine. I opened a new tab first and then entered the address. I tried to re-open the tab and even to reload it, but the result is always the same. It really sucks because now I can't allow certain scripts that are required to properly use it. It does still show a number on the uMatrix icon (329).

**Comment by dkrmr** [comment]
I have the same issue but for me it appears on every sites, even after multiples page reload or firefox reboot. :/
But curiously, the icon display the number of allowed requests: https://imgur.com/OcX0zZn

**Comment by gorhill** [comment]
Just a screenshot without more info is not really useful. Browser? Version? Browser console? How about in a fresh profile? Etc.

**Comment by SlavicB** [comment]
Managed to reproduce by changing the browser's 'Accept cookies from websites' setting.
https://i.imgur.com/CS3d46r.png
When unticked the popup panel is blank on all sites.

It was working previously and then (must be an update) stopped.

**Comment by cedricbonhomme** [comment]
I confirm the comment of @SlavicB .
I have to tick 'Accept cookies from websites' in the configuration of Firefox. Else the pop-up panel is blank on all web sites.

**Comment by cedricbonhomme** [comment]
I just did an update of uMatrix today. This should probably be related.

**Comment by cedricbonhomme** [comment]
When 'Accept cookies from websites', in the browser console of Firefox the message below is displayed when I click on the icon of uMatrix.

```bash
SecurityError: The operation is insecure.  popup.js:38
	<anonymous> moz-extension://0deb699d-4659-4b18-8a89-b2a2b9fa99c0/js/popup.js:38:9
	<anonymous> moz-extension://0deb699d-4659-4b18-8a89-b2a2b9fa99c0/js/popup.js:37:2
	<anonymous> moz-extension://0deb699d-4659-4b18-8a89-b2a2b9fa99c0/js/popup.js:30:2
```

**Comment by gorhill** [comment]
Thanks for the info. I will publish a fix asap.

**Comment by cedricbonhomme** [comment]
You're welcome. I am fan of your extensions :-)

**Comment by gorhill** [comment]
1.1.16 is now available on AMO.

Hopefully this was also the issue suffered by OP.

**Comment by cedricbonhomme** [comment]
Just updated. This solved the problem for me. This was a very quick fix. Thanks a lot!

**Comment by seniorpandabear** [comment]
Hello!

I have a similar problem while using Chrome, which renders the plugin unusable. It looks like this:
https://i.imgur.com/jJptvCQ.jpg

The interface was degrading slowly. First, only the numbers started to disappear
from the dropdown interface. I kept using it since it was still fairly usable.
Now however, I cannot set anything up for new sites. Old filters still seem to work.

I have tried to clear the browser's cache, temporary files, removing and readding the extension, resetting the extensions settings. Nothing has worked. I have all cookies enabled in the browser, so my problem does not seem to be solved in the same way as previous posters.

Thank you in advance!

**Comment by gorhill** [comment]
What do you mean exactly by "missing numbers"?

**Comment by seniorpandabear** [comment]
Thank you for your reply.

By "missing numbers" I mean that when you click the button to bring out the drop-down uMatrix interface, there would usually be little numbers next to the top row buttons/icons (Disable/Enable matrix, Revert changes, etc). However these started disappearing a while ago. I'm guessing a few patches ago.

My chrome version is  39.0.2171.95 m.

Certain sites have a way of blocking you out when you use an older browser, so I made good use of the UA-spoofing function to pretend I'm on a later browser. I was thinking the missing numbers, broken interface, missing Privacy tab then missing spoofing function was caused by file corruption. But apparently it was just the updates! :) 

I thought it would be cool to keep/reintroduce that UA-spoofing function, even though it won't be carrying out its intended purpose for privacy, it is still useful for tricking certain sites (such as YouTube) that you're using a newer browser. Perhaps with a "Use at your own risk!"-disclaimer, saying that it's more of a gimmick and in some cases will actually leak the real UA, but that some people could still find it useful to bypass basic "old browser" blocks on websites.

**Comment by gorhill** [comment]
Your Chrome version is too old. You need v45 minimum.

**Comment by seniorpandabear** [comment]
Hmm, what changed recently to make it incompatible with version 39? It was working fine up until a few days ago. I think it was patch 1.1.14 that broke it entirely.

I use this version on one of my machines that has a very weak CPU. The later chome versions use 16-26% cpu when idle, while this version uses only 2-3%.

**Comment by seniorpandabear** [comment]
I don't know much about programming but sounds like it would add unnecessary extra work for you to fix this, so I completely understand if you want to use your time and coding syntax in a more time-efficient manner - Thank you still for this great extension! (and that you took the time to reply)

**Comment by T-vK** [comment]
Using a 3 years old browser is absolutely insane. I see no reason to support that. The list of known critical exploits is longer than you could possibly imagine. 
I say, support the latest 3 versions and be done with it. Maybe also support Firefox ESR.

Instead of polyfilling you could also transpile using babel for instance. And you could also use code optimizers like the closure-compiler to improve performance. Using gulp you can fully automate the process, so there would be no "burden" anymore.
