### ISSUE TITLE
bring back ua spoofing?

### ISSUE THREAD

**Issue by Zhangsun321** [gorhill/uMatrix#927]
I miss the user agent spoofing/rotating between list of ua's!

**Comment by ArchangeGabriel** [comment]
It won’t come back. Spoofing UA is something that should be done very precisely, and the current state of affairs shows that it is really hard. Even for the Tor Browser, as part of their uplift work toward Firefox, they are renouncing in spoofing the UA to a different OS (and same goes for browser, although it does not apply here), because this is very easily detectable. See e.g. how https://browserprint.info/ or https://browserleaks.com/ip can detect the correct OS even with UA spoofing to another.

**Comment by uBlock-user** [comment]
You can use ScriptSafe for that, if you really miss it that badly.
