### ISSUE TITLE
Report more accurately that resources are being blocked following page load

### ISSUE THREAD

**Issue by Alpengreis** [gorhill/uMatrix#938]
I can't load the following page correctly if uMatrix extension enabled.:

https://www.chess.com/analysis-board-editor?fen=5Q2%2F3R3p%2F8%2Fr1N2Npk%2F5p2%2F5P2%2F6PK%2F8+b+-+-+5+54&flip=false&tab=computerAnalysis&diagramType=daily

Here the correct page if uMatrix extension is deactivated (not deinstalled):
![analyses_ok](https://user-images.githubusercontent.com/11355601/35645429-0edae678-06cc-11e8-9ff5-bba1c1fc6262.jpg)

and here the incorrect page if uMatrix extension is enabled and disabled for this page:
![analyses_not-ok](https://user-images.githubusercontent.com/11355601/35645438-16221e06-06cc-11e8-8fb6-e835376b5c92.jpg)

Data:
OS = Win 10 Pro 65.0.3325.31 Build 1709 64 bit
Browser = Chrome Dev 65.0.3325.31 64 bit
uMatrix = 1.3.3b2
uMatrix Setting should be not relevant because it's disabled completely for this page
Browser Setting should be not relevant because it works if uMatrix extension is deactivated

What is here the problem?

PS: Firefox Dev (59.0b5) loads the page graphical correct but the anylysis does not run right (stops after 2 moves or so) - for that you would need an account on chess.com but should be not YET relevant at this point (I hope if the page loads correctly in Chrome this does also solve the problem in Fx).

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uMatrix/wiki/About-%22the-page-is-still-broken-after-I-created-all-necessary-rules%22

**Comment by gorhill** [comment]
Are you blocking web workers?

**Comment by Alpengreis** [comment]
@gorhill OMG, I had indeed "no-workers: * true" and yes, after whitelisting the site, it works ...

I hope I will never forget that case - thank you so much!!

**Comment by gorhill** [comment]
I am going to use this issue to fix two things:
- Make the badge reports block count
- Inline script tags reported as blocked resources even when it's not the case

The point is that just the color of the icon should be enough to convey that there are stuff still blocked. In the current case the icon still had red in it, so there was a hint that someghing was still blocked.

The badge is just to make this more obvious.

 Even after allowing all, the icon still had red in it, because of the inline script tag issue above.
